### ISSUE TITLE
Missing @Output() onToggleExpanded;

### ISSUE THREAD

**Issue by JulienNexonia** [500tech/angular2-tree-component#100]
Missing output onToggleExpanded in tree.component.ts
Can you add this output ?
Thanks.
Julien

**Comment by adamkleingit** [comment]
Will do in the coming version

**Comment by adamkleingit** [comment]
Fixed in 1.3.6 - can you check?

**Comment by JulienNexonia** [comment]
Works fine on 1.3.6.
Thanks
