### ISSUE TITLE
Firefox compatibility issue

### ISSUE THREAD

**Issue by pkhruasu-ui** [500tech/angular2-tree-component#101]
Hi,

The library does not seem to work in our Firefox and even on the demo page.

Firefox version : 49.0.2
Library version : 1.3.5

Could you please let me know if this is a new issue or it was fixed?

**Comment by adamkleingit** [comment]
Minor problem in the example.
Fixed in 1.3.6 - can you check?

**Comment by adamkleingit** [comment]
Hey, if this happens again please reopen. Thanks
