### ISSUE TITLE
treeModel.cancelDrag() Why not work?

### ISSUE THREAD

**Issue by philipbo** [500tech/angular2-tree-component#104]
Ask for help, thanks all.
`treeModel.cancelDrag()` Why not work?

    @ViewChild(TreeComponent)
    private tree: TreeComponent;

    treeOptions = {
        isExpandedField: 'expanded',
        getChildren: this.getChildren.bind(this),
        idField: 'uuid',
        allowDrag: true
    };

    onMoveNode($event) {
        if (true){
            this.tree.treeModel.cancelDrag();
        }
        this.tree.treeModel.update();
    }

**Comment by adamkleingit** [comment]
onMoveNode happens after drag was already finished and the node has moved.

You can override actionMappings and move the node only in certain conditions. Something like this:
actionMapping: {
  mouse: {
    drop: (tree:TreeModel, node:TreeNode, $event:any, to:{ node:TreeNode, index: number }) => {
      if (node.something) {
        TREE_ACTIONS.MOVE_NODE(tree, node, $event, to);
     }
    }
  }
}

**Comment by philipbo** [comment]
@adamkleingit 
thank you very much.
it's ok. 👍
