### ISSUE TITLE
Option isActiveField, isFocusedField

### ISSUE THREAD

**Issue by antoschd** [500tech/angular2-tree-component#105]
Is there a way to set a node active or focused by field?

Would be awesome to have options like:
**options = { isActiveField: 'active' }** and **options = { isFocusedField: 'focused' }**

**Comment by JeremiasIsnardy** [comment]
I agree, such options would be nice.

Or is there any other way to set a specific node from the list to active/focused when the nodes get loaded?

**Comment by adamkleingit** [comment]
Hey,
you can always locate the nodes by id / path / whatever, and then call `setIsActive(true)` method,
or `setIsActive(true, true)` to do multi select.
