### ISSUE TITLE
TreeNodes with children not aligned with childless TreeNodes

### ISSUE THREAD

**Issue by JulienNexonia** [500tech/angular2-tree-component#107]
#44 follow-up
After upgrading to version 2.0.0, it seems that the misalignment is still around :
![00](https://cloud.githubusercontent.com/assets/2727742/20586625/f6e6eb88-b259-11e6-8a14-d5030ffde2ac.png)
Thanks.
Julien

**Comment by adamkleingit** [comment]
Fixed in 2.1.0

**Comment by JulienNexonia** [comment]
Thanks
