### ISSUE TITLE
getDragNode   function error in 2.4.0

### ISSUE THREAD

**Issue by tomalex0** [500tech/angular2-tree-component#113]
Hi,
I tried migrating from  `1.3.6` to `2.4.0`, getting error during build  in below snippet
Angular version : 2.2.1

`Property 'getDragNode' does not exist on type 'TreeModel'.`

```
  drop: (tree:TreeModel, node:TreeNode, $event:any, {from, to}) => {

                 let tObj = tree.getDragNode();
                let sNode = tObj.node.children[tObj.index];
                let tNode = to.node;
             
                
                let resultLvl = tNode.level + ( sNode.hasChildren? 1 : 0);
                if(resultLvl < 3 ){
                    
                    TREE_ACTIONS.MOVE_NODE(tree,node,$event,to);
                }else {
                    console.log('reject. Too many level');
                }
   }
```

**Comment by thohoh** [comment]
Same here, is there updated doc section about it?

**Comment by thohoh** [comment]
@tomalex0 I figured it out, fourth argument in mouse drop handler is { from , to }  <--- 'from' is an actual dragged node.

**Comment by adamkleingit** [comment]
Hey guys,
2.X.X had breaking changes.

The docs are updated:
[https://angular2-tree.readme.io/docs/drag-drop](https://angular2-tree.readme.io/docs/drag-drop)

And CHANGELOG.md specifies all changes and breaking changes between versions:
[https://github.com/500tech/angular2-tree-component/blob/master/CHANGELOG.md](https://github.com/500tech/angular2-tree-component/blob/master/CHANGELOG.md)
