### ISSUE TITLE
isExpanded = true now working when data is dynamicly added to onde

### ISSUE THREAD

**Issue by tturalija** [500tech/angular2-tree-component#115]
I wish to expand whole tree at start, but property isExpanded  is ignored when nodes are added after component creation (on mouse click, on server response etc...).

Tested on version: 2.4.0
Similar bugs:
https://github.com/500tech/angular2-tree-component/issues/21
https://github.com/500tech/angular2-tree-component/issues/81 

Code example to reproduce problem.
this.nodes= new Array<any>();
 onButton(){
    this.nodes= this.nodesToBeAddedOnClickOrServerRequest ;
  }
  nodesToBeAddedOnClickOrServerRequest = [
    {
      id: 1,
      name: 'root1',
      isExpanded: true,
      children: [
        { id: 2, name: 'child1' },
        { id: 3, name: 'child2' }
      ]
    },
    {
      id: 4,
      name: 'root2',
      isExpanded: true,
      children: [
        { id: 5, name: 'child2.1' },
        {
          id: 6,
          name: 'child2.2',
          children: [
            { id: 7, name: 'subsub' }
          ]
        }
      ]
    }
  ];

Problem is in update function.   this._calculateExpandedNodes() will never get called because this.firstUpdate is set to false in initialization.

if (this.firstUpdate) {
            if (this.roots) {
                this.fireEvent({ eventName: events_1.TREE_EVENTS.onInitialized });
                this.firstUpdate = false;
                this._calculateExpandedNodes();
            }
        }

**Comment by adamkleingit** [comment]
Hey,
the `isExpanded` feature is known to be problematic. Since I don't bind anything directly to properties of the nodes, I have to guess when the user wants isExpanded to actually expand the nodes, and my best guess is when the tree is first created, or when nodes are added asynchronously.

I have to rethink this whole feature.
