### ISSUE TITLE
Allow prevention of dropping on individual trees nodes

### ISSUE THREAD

**Issue by ErgoSoftUK** [500tech/angular2-tree-component#116]
Consider a tree where drop should be prevented on only some nodes within a tree (perhaps a folder/item tree where certain item types can only be dropped in certain folders, and folders cannot be dropped "into" items).

Since the implementation of cross-tree dragging, there are potentially many more scenarios where this may be required.  For example a report builder with a tree on the left containing components, and a tree on the right containing the report structure.  Both trees need "allowDrag" (so component nodes can be dragged onto the report from the component tree, and the report structure can be altered by dragging nodes within the report tree).  However, it should not be possible to drag nodes from the report to the component tree, or re-order/restructure the nodes within the component tree itself.

It would therefore be useful to be able to provide a function that takes a from/to node and returns a boolean to denote if that drop is allowed.  Ideally this would be called at the mouseOver event (rather than mouseDrop) so the UI (drop target, mouse pointer, etc) could be rendered accordingly.

**Comment by adamkleingit** [comment]
Good idea, then I should call the allowDrop function on drag start, not on
mouse over to be more performant

**Comment by ErgoSoftUK** [comment]
I can understand that you'd want to make the call on dragStart rather than mouseOver from a performance point of view, but I'm not sure how you'd accomplish this if the permission to drop is dependant upon the node being dropped on?

**Comment by adamkleingit** [comment]
Hey,
added in 2.5.0.

I ended up invoking the function onDragOver - makes more sense than calling it on all the nodes at once onDragStart.

Thanks!

**Comment by adamkleingit** [comment]
I meant I will call all possible drop locations on drag start.
But eventually I decided it would be more performant just to call it
onDragOver only for the specific drop location.


-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633
