### ISSUE TITLE
[Question] : Get Parent

### ISSUE THREAD

**Issue by F3L1X79** [500tech/angular2-tree-component#119]
Hello,
Thank you for the great module!

This is not an issue, but is it possible to get the parent of a node (ie on click) because I'm not seeing it in the doc nor in these issues?
Thanks.

**Comment by davidrodriguez** [comment]
I was able to get the parent of the selected node by using the following: node.parent.data.id
ex)
    private deleteNode($event, tree, node) {
        //$event.stopPropagation();
        let treeNode: TreeNodeDTO = new TreeNodeDTO(
            node.data.id, node.parent.data.id, 0, node.data.name, []
        );

**Comment by kaleemullah360** [comment]
How can I get the new parent after dragging and dropping a node into another node,
i.e `onMoveNode` I am able to get current moved node but I can't get that node's new root/oparent naode. please help

**Comment by F3L1X79** [comment]
If it's not with `node.parent.data.id` , then I don't know how the DOM is generated after the drag & drop. Maybe you should open your own issue because this one is closed.

**Comment by adamkleingit** [comment]
you have a 'to' object with all the needed data

**Comment by kaleemullah360** [comment]
Thank you, I got it. `to` contains parent node.
