### ISSUE TITLE
Select with keys (Action Mapping)

### ISSUE THREAD

**Issue by denkomanceski** [500tech/angular2-tree-component#120]
Hi, what is the best approach to override the action mappings to select the node with the keys (up,down,left,right) instead of focusing it ? Overriding with:
```
TREE_ACTIONS.DRILL_DOWN(tree, node, $event);
 TREE_ACTIONS.SELECT(tree, node, $event);
``` 
wont work because it will select + focus the old one

**Comment by adamkleingit** [comment]
You should probably call the original action,
and then once the new node is focused call `treeModel.getFocusedNode().setIsActive(true)`.
