### ISSUE TITLE
Drag node outside of tree

### ISSUE THREAD

**Issue by Faey2222** [500tech/angular2-tree-component#122]
Hello

unfortuantely I can't get the function "Drag a node outside of the tree" to work. I implemented it to my component as described in the docs but always get this error:

> zone.js:388Unhandled Promise rejection: Template parse errors:
> Can't bind to 'treeAllowDrop' since it isn't a known property of 'div'. ("
> </ul>
> 
>     <div (treeDrop)="onDrop($event)" [ERROR ->][treeAllowDrop]="allowDrop.bind(this)"></div>
> 
> 
> "): PagebarComponent@5:37 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
> Can't bind to 'treeAllowDrop' since it isn't a known property of 'div'. ("
> </ul>
> 
>     <div (treeDrop)="onDrop($event)" [ERROR ->][treeAllowDrop]="allowDrop.bind(this)"></div>

I looked in the code and found that treeDropAllow (as described in the docs) doesen't exist but treeAllowDrop does but it makes no difference.

I'm trying to drag an node from the tree to a trash-icon of mine. Is this an error in the Angular2-Tree component or a mistake I may be doing?

**Comment by elerocks** [comment]
don't forget to import TreeDropDirective (this could probably be mentioned in docs), i.e.
`import { TreeComponent, TreeDropDirective } from 'angular2-tree-component';
`

and as you mentioned, there is a typo in docs, it should be treeAllowDrop:
`<div style="width:400px; height:400px; background:green" (treeDrop)="onDrop($event)"     [treeAllowDrop]="allowDrop.bind(this)"></div>`

**Comment by adamkleingit** [comment]
@elerocks Why should he import the directive? It's part of the module declarations
@Faey2222 did this work out? I don't see a reason why it shouldn't work.

I updated the docs

**Comment by adamkleingit** [comment]
@Faey2222 Any news on this? I'm closing the issue. Please re-open it if the problem still persists.
Thanks
