### ISSUE TITLE
Getting index of node template - let-i="index" shows nothing

### ISSUE THREAD

**Issue by snstarosciak** [500tech/angular2-tree-component#129]
Hello, in this documentation, it says you can use `<template>` tags to customize the inner content, which is awesome! However, I'm trying to access the tree node's index in each template. When I try `let-i="index"`, it doesn't provide the index :/ Is there anything I can do to do this? I'd like to be able to show something like `Section {{i + 1}}` for creating "sections"

Here is a sample from the docs related to templating, for reference:

```
<Tree [nodes]="nodes">
  <template #treeNodeTemplate let-node>
    <span>{{ node.data.name }}</span>
    <button (click)="go($event)">Custom Action</button>
  </template>
</Tree>
```

Thanks!

**Comment by adamkleingit** [comment]
This is easy to add to the code. I would appreciate if you make a pull request!
If not - I'll try to get to it in the coming 2 weeks

Thanks.

**Comment by adamkleingit** [comment]
Added in 2.6.0
Use: let-index="index"

Good luck!

**Comment by snstarosciak** [comment]
@adamkleingit Hey man, thanks so much for taking care of that. I hadn't had a chance to look at this again until tonight and it works flawlessly! 

Cheers!
