### ISSUE TITLE
fails to install unless typings is installed globally

### ISSUE THREAD

**Issue by seiyria** [500tech/angular2-tree-component#13]
I'm not using Typescript so I don't have nor use `typings`. It fails to install in the postinstall step as a result. I saw that the path is `node_modules/.bin/typings install` - you should just be able to say `typings install` and it should install based on the depended-on install of typings - no need to specify the full path.

**Comment by 500tech-user** [comment]
Oh I see. It's because typings is in the devDependencies and not
dependencies.
But if I write just 'typings install', and you don't have it installed
globally, it will fail - no?

On Wed, Jul 6, 2016 at 7:03 PM, Kyle J. Kemp <notifications@github.com>
wrote:

> I'm not using Typescript so I don't have nor use typings. It fails to
> install in the postinstall step as a result. I saw that the path is node_modules/.bin/typings
> install - you should just be able to say typings install and it should
> install based on the depended-on install of typings - no need to specify
> the full path.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/500tech/angular2-tree-component/issues/13>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACUsQ-zNQOObNEsGebsJ99lEObdIAAP6ks5qS9HngaJpZM4JGPV3>
> .
>



-- 
*Adam Klein*
*CTO & Co-Founder*
*Tel.* +972-52-747-5633
*blog.500tech.com <http://blog.500tech.com>*
meetup.com/angularjs-il

**Comment by seiyria** [comment]
It should be a dependency unless you make it optional.

No, node adds the .bin directory to the path automatically (try it out) so it is extraneous.

**Comment by 500tech-user** [comment]
How would you do typings install as optional? Need to check if typings is
installed.
Something like a bash script?

On Thu, Jul 7, 2016 at 3:49 PM, Kyle J. Kemp <notifications@github.com>
wrote:

> It should be a dependency unless you make it optional.
>
> No, node adds the .bin directory to the path automatically (try it out) so
> it is extraneous.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/500tech/angular2-tree-component/issues/13#issuecomment-231067826>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACUsQyKYOEpLPZrME8Q7sNglStlT71nRks5qTPXkgaJpZM4JGPV3>
> .
>



-- 
*Adam Klein*
*CTO & Co-Founder*
*Tel.* +972-52-747-5633
*blog.500tech.com <http://blog.500tech.com>*
meetup.com/angularjs-il
