### ISSUE TITLE
cannot read getIndexInParent of null

### ISSUE THREAD

**Issue by DianaSellarova** [500tech/angular2-tree-component#131]
The node that is being moved is null and i get this error, but very randomly. Sometimes drag and drop of tree works perfectly, sometimes not and stops working at all. I checked a lot of things but can't seem to find where is the problem. It usually happens only after first drag&drop.

edit : it looks like onDragStart is called after all previous functions including onDrop where this.treeDraggedElement.get() returns null

error_handler.js:48 EXCEPTION: Error in ./TreeNodeDropSlot class TreeNodeDropSlot - inline template:3:6 caused by: Cannot read property 'getIndexInParent' of null
ErrorHandler.handleError @ error_handler.js:48
next @ application_ref.js:298
schedulerFn @ async.js:89
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:81
NgZone.triggerError @ ng_zone.js:280
onHandleError @ ng_zone.js:259
ZoneDelegate.handleError @ zone.js:236
Zone.runGuarded @ zone.js:131
NgZone.runGuarded @ ng_zone.js:133
outsideHandler @ dom_events.js:30
ZoneDelegate.invokeTask @ zone.js:265
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:335
error_handler.js:50 ORIGINAL EXCEPTION: Cannot read property 'getIndexInParent' of null
ErrorHandler.handleError @ error_handler.js:50
next @ application_ref.js:298
schedulerFn @ async.js:89
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:81
NgZone.triggerError @ ng_zone.js:280
onHandleError @ ng_zone.js:259
ZoneDelegate.handleError @ zone.js:236
Zone.runGuarded @ zone.js:131
NgZone.runGuarded @ ng_zone.js:133
outsideHandler @ dom_events.js:30
ZoneDelegate.invokeTask @ zone.js:265
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:335
error_handler.js:53 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:53
next @ application_ref.js:298
schedulerFn @ async.js:89
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:81
NgZone.triggerError @ ng_zone.js:280
onHandleError @ ng_zone.js:259
ZoneDelegate.handleError @ zone.js:236
Zone.runGuarded @ zone.js:131
NgZone.runGuarded @ ng_zone.js:133
outsideHandler @ dom_events.js:30
ZoneDelegate.invokeTask @ zone.js:265
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:335
error_handler.js:54 TypeError: Cannot read property 'getIndexInParent' of null
    at TreeModel.moveNode (tree.model.js:354)
    at MOVE_NODE (tree-options.model.js:21)
    at TreeNode.mouseAction (tree-node.model.js:307)
    at TreeNodeDropSlot.onDrop (tree-node-drop-slot.component.js:17)
    at _View_TreeNodeDropSlot0._handle_treeDrop_1_0 (component.ngfactory.js:68)
    at view.js:375
    at SafeSubscriber.schedulerFn [as _next] (async.js:101)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:223)
    at SafeSubscriber.next (Subscriber.js:172)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at EventEmitter.Subject.next (Subject.js:55)
    at EventEmitter.emit (async.js:81)
    at TreeDropDirective.onDrop (tree-drop.directive.js:52)
    at _View_TreeNodeDropSlot0._handle_drop_1_3 (component.ngfactory.js:89)
    at view.js:375
    at dom_renderer.js:262
    at dom_events.js:30
    at ZoneDelegate.invoke (zone.js:232)
    at Object.onInvoke (ng_zone.js:238)
    at ZoneDelegate.invoke (zone.js:231)
    at Zone.runGuarded (zone.js:128)
    at NgZone.runGuarded (ng_zone.js:133)
    at HTMLDivElement.outsideHandler (dom_events.js:30)
    at ZoneDelegate.invokeTask (zone.js:265)
    at Zone.runTask (zone.js:154)
    at HTMLDivElement.ZoneTask.invoke (zone.js:335)
ErrorHandler.handleError @ error_handler.js:54
next @ application_ref.js:298
schedulerFn @ async.js:89
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:81
NgZone.triggerError @ ng_zone.js:280
onHandleError @ ng_zone.js:259
ZoneDelegate.handleError @ zone.js:236
Zone.runGuarded @ zone.js:131
NgZone.runGuarded @ ng_zone.js:133
outsideHandler @ dom_events.js:30
ZoneDelegate.invokeTask @ zone.js:265
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:335
error_handler.js:57 ERROR CONTEXT:
ErrorHandler.handleError @ error_handler.js:57
next @ application_ref.js:298
schedulerFn @ async.js:89
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:81
NgZone.triggerError @ ng_zone.js:280
onHandleError @ ng_zone.js:259
ZoneDelegate.handleError @ zone.js:236
Zone.runGuarded @ zone.js:131
NgZone.runGuarded @ ng_zone.js:133
outsideHandler @ dom_events.js:30
ZoneDelegate.invokeTask @ zone.js:265
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:335
error_handler.js:58 DebugContext {_view: _View_TreeNodeDropSlot0, _nodeIndex: 1, _tplRow: 3, _tplCol: 6}
ErrorHandler.handleError @ error_handler.js:58
next @ application_ref.js:298
schedulerFn @ async.js:89
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:81
NgZone.triggerError @ ng_zone.js:280
onHandleError @ ng_zone.js:259
ZoneDelegate.handleError @ zone.js:236
Zone.runGuarded @ zone.js:131
NgZone.runGuarded @ ng_zone.js:133
outsideHandler @ dom_events.js:30
ZoneDelegate.invokeTask @ zone.js:265
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:335
zone.js:158 Uncaught ViewWrappedError {_nativeError: Error: Error in ./TreeNodeDropSlot class TreeNodeDropSlot - inline template:3:6 caused by: Cannot re…, originalError: TypeError: Cannot read property 'getIndexInParent' of null
    at TreeModel.moveNode (http://localho…, context: DebugContext, longStack: "TypeError: Cannot read property 'getIndexInParent'…tp://localhost:3000/polyfills.bundle.js:15410:33)"}

**Comment by adamkleingit** [comment]
Do you have any custom options regarding drag and drop? Can you share your
code?

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by DianaSellarova** [comment]
i tried your tree from demo i copied everything and it still happens, i used nodes from your example with the allowDrag: true in options... i tried to put some breakpoints in whole tree library and the onDragStart function is just called too late... randomly... but most of the time it doesn't work

i tried it all with my own tree as well 
data : (response from request)
`[
          {
            "data": {
              "x": 15,
              "y": 19,
              "z": 0,
              "width": 200,
              "height": 150,
              "id": 605,
              "typeId": -5,
              "type": "TEXT",
              "typeName": "title",
              "value": "title",
              "canvasId": "elem-logicMaster-597-1"
            },
            "nodes": []
          },
          {
            "data": {
              "x": 221,
              "y": 19,
              "z": 0,
              "width": 200,
              "height": 150,
              "id": 606,
              "typeId": -4,
              "type": "TEXT",
              "typeName": "subtitle",
              "value": "subtitle",
              "canvasId": "elem-logicMaster-597-2"
            },
            "nodes": []
          }
        ]`

html : 
`<Tree
                                #tree
                                [nodes]="logic.elements.nodes"
                                [options]="customTreeOptions"
                                (onEvent)="onEvent($event)"
                                (onMoveNode)="onMoveNode($event)"
                        >
                            <template #treeNodeTemplate let-node>
                                <span>{{ node.data.data.value }}</span>
                                
                            </template>
                            <template #loadingTemplate>Loading, please hold....</template>
                        </Tree>`

options: 
`
customTreeOptions = {
        isExpandedField: 'expanded',
        // actionMapping,
        allowDrag: true
    }`

**Comment by adamkleingit** [comment]
Can you say which browser version and angular2-tree-component versions are
you using?

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by DianaSellarova** [comment]
"angular2-tree-component": "^2.5.1", and Chrome 55.0.2883.95

**Comment by adamkleingit** [comment]
What version of Angular are you using?
Can you try to remove node_modules folder and npm install again?

**Comment by DianaSellarova** [comment]
5.1.1
a tried, and it still didnt help

**Comment by adamkleingit** [comment]
Hi, which version of Angular are you using?
5.1.1 is not an Angular version

**Comment by DianaSellarova** [comment]
angular 2 of course.. i already solved the problem in my project, after versions of angular and material design where changed, it started working properly

**Comment by adamkleingit** [comment]
OK closing the issue.
BTW I meant which version exactly, like 2.4.4 etc. Obviously it's Angular 2 :)
