### ISSUE TITLE
actionMapping drop seems to supply only droplocation node, not dragged node. Tried to use drag and dragStart actionmapping but don't seem to be called at all.

### ISSUE THREAD

**Issue by HenricusL** [500tech/angular2-tree-component#132]
Hi,

Please look for an answer in the docs before submitting an issue:
angular2-tree.readme.io.

In case you are reporting a bug, please specify which version of angular2-tree-component you are using.

Thank you

**Comment by adamkleingit** [comment]
Use `from` to get the dragged node.
From the docs:
```
  actionMapping: {
    mouse: {
      drop: (tree:TreeModel, node:TreeNode, $event:any, {from, to}) => {
        // use from to get the dragged node.
        // use to.parent and to.index to get the drop location
        // use TREE_ACTIONS.MOVE_NODE to invoke the original action
      }
    }
  }
```

Thanks @HenricusL

**Comment by HenricusL** [comment]
thanks. updating to the latest version solved this.

**Comment by 1010451** [comment]
for drop we use "drop: (tree:TreeModel, node:TreeNode, $event:any, {from, to})"
and for drag, dragstart and dragend? what we is it?
thx
