### ISSUE TITLE
Drag shadow customize

### ISSUE THREAD

**Issue by denkomanceski** [500tech/angular2-tree-component#133]
Hi, Is there any way how to disable/customize the shadow that is shown when dragging a node on the tree? It is not very clear where the user is dropping the node, I would like to make it a bit more "precise". Here is how it looks now (http://prntscr.com/dmlj0j). Even the branch lines are showing on the shadow.

Regards
D

**Comment by adamkleingit** [comment]
Hi,
the screenshot you sent doesn't show a dragged node, so I don't know
exactly what you are referring to

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by denkomanceski** [comment]
It does, the node is in red square with arrow. The mouse is not there since I could not make a screenshot + drag at the same time. Here is another one (which shows how hard it is to see where you are dropping/able to drop) http://prntscr.com/dmlycx

**Comment by adamkleingit** [comment]
You have classes for the drop node that you can use, and also for the drop
slots between nodes:
```
.node-content-wrapper.is-dragging-over
.node-content-wrapper.is-dragging-over-disabled
.node-drop-slot.is-dragging-over
```

The default style is very visible:
[image: Inline image 1][image: Inline image 2]

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by adamkleingit** [comment]
Sorry, here are the images:
![screen shot 2016-12-22 at 4 00 25 pm 2](https://cloud.githubusercontent.com/assets/889418/21427936/024148d6-c860-11e6-9e7c-abe6cb4c6a36.png)
![screen shot 2016-12-22 at 4 00 28 pm 2](https://cloud.githubusercontent.com/assets/889418/21427937/02433790-c860-11e6-958c-3de4604306e1.png)

**Comment by denkomanceski** [comment]
Thanks, but these classes are for the containers that are shown underneath. I want to customize/remove the shadow when I am dragging. This shadow: http://prntscr.com/dmmf5a. Because its too big and its hard to see on which node you are dragging.
