### ISSUE TITLE
how to find active node (onActiveChanged does not fire)

### ISSUE THREAD

**Issue by dakipro** [500tech/angular2-tree-component#134]
Hi,
I checked all the documentation on how to get the active/selected node and didn't find a clear example so I assume that onActiveChanged is what I need. I am using 2.5.1 version (that is what "npm show angular2-tree-component version" says)

I need to have currently selected node in the component.ts (as a filter, f.eks. SelectedCategoryId), and also to have 0 when none is activated. So I was looking for something like "getActiveNode" and closest to that (I think is onActiveChanged ?).
When I try the example 
`<Tree [nodes]="nodes"
    (onEvent)="onEvent($event)"
  </Tree>`
the method  onEvent = ($event) => console.log($event); only logs 
item-list.component.ts:133 Object {eventName: "onFocus", node: TreeNode}
item-list.component.ts:133 Object {eventName: "onFocus", node: TreeNode}
item-list.component.ts:133 Object {eventName: "onActivate", node: TreeNode}
item-list.component.ts:133 Object {eventName: "onBlur", node: TreeNode}
item-list.component.ts:133 Object {eventName: "onBlur", node: TreeNode}
item-list.component.ts:133 Object {eventName: "onFocus", node: TreeNode}
item-list.component.ts:133 Object {eventName: "onFocus", node: TreeNode}

no matter were I click or navigate with keyboard. How to reliably get the currently active/selected node and detect its change and deactivaon?

**Comment by adamkleingit** [comment]
Hey,
the treeModel can give you all the API you need.
Check out the API section of the readme, under ITreeModel:
https://angular2-tree.readme.io/docs/api

Or just the public functions in the code:
https://github.com/500tech/angular2-tree-component/blob/master/lib/models/tree.model.ts


And the answer to your question, is not surpringly:
treeModel.getActiveNode()
or
treeModel.getActiveNodes()
If you're using multiselect.

All the best!

**Comment by dakipro** [comment]
Hi Adam, thank you for your answer. 
Being new to angular I am struggling a bit to get it to work, hope that you can point me to a right direction. 
I tried code from example 
<Tree #tree [nodes]="categoriesTree" (onEvent)="onCategoriesEvent($event)" [options]="treeOptions"></Tree>

and then in controller before constructor I have 

  @Input() src: string;
  @ViewChild('tree') tree;

and I can access it like this.tree.treeModel
However there is no method getActiveNode() on it. There is a property activeNodes which is an array of active nodes, and I can (usually) get first node ID like this.tree.treeModel.activeNodes[0].id but it is quite fiddly.

Am I close to the solution, is this the method you are referring to?

Thanks in advanced!

**Comment by dakipro** [comment]
Hi @adamkleingit , I think I am very close to the solution, I would appreciate if you could just look into my previous comment, I cannot seem to find the method you mention.
Thank you for helping me, I really appreciate your time
