### ISSUE TITLE
Don't Apply style css!

### ISSUE THREAD

**Issue by johndiego** [500tech/angular2-tree-component#135]
**Style**
`.tree {
  width: 100%;
  background: red;
}

.node-content-wrapper {
  display: flex;
  flex-wrap: wrap;
  align-items: baseline;
}

.node-content-wrapper {
  flex-grow: 1;
  position: relative;
}

.pull-right {
  position: absolute;
  right: 10px;
}
`
**Component **
`

import { Component } from '@angular/core';

@Component({
    selector: 'main-sidebar',
    templateUrl: 'main-sidebar.component.html',
    styleUrls: ['main-sidebar.component.scss']
})
export class MainSidebarComponent {
  nodes = [
    {
      id: 1,
      name: 'root1',
      children: [
        { id: 2, name: 'child1' },
        { id: 250, name: 'child23',

        children: [
          { id: 87, name: 'child2221' },
          { id: 150, name: 'child2'

         }
        ]

       }
      ]
    },
    {
      id: 4,
      name: 'root2',
      children: [
        { id: 5, name: 'child2.1' },
        {
          id: 6,
          name: 'child2.2',
          children: [
            { id: 7, name: 'subsub' }
          ]
        }
      ]
    }
  ];

}
`
**Template HTML**
`
<Tree [nodes]="nodes"></Tree>

`

![image](https://cloud.githubusercontent.com/assets/18476845/21487243/d6864d78-cbab-11e6-99eb-28ce516b3a7f.png)

**How solved this?**

**Comment by adamkleingit** [comment]
Hey,
try using more specific style rules using your own class.
For example:
```
.my-tree .node-content-wrapper {
  ...
}
```

If that doesn't work use !important.

Good luck

**Comment by Hesesses** [comment]
I'm having the same problem. Custom css is not applied to the tree. I also tried !important
