### ISSUE TITLE
Accessing instance of the leaf component

### ISSUE THREAD

**Issue by denkomanceski** [500tech/angular2-tree-component#136]
Hi, I am using the tree like this
```
<div class="slds-panel slds-grid" style="height: 800px; overflow-y: auto">
  <Tree (onFocus)="nodeFocused($event)" (onInitialized)="refreshState()" (onMoveNode)="onMoveNode($event)" [nodes]="nodes" [options]="options">
    <template #treeNodeTemplate let-node>
        <adl-archetype-tree-leaf [contextMenu]="basicMenu" [node]="node"></adl-archetype-tree-leaf>
    </template>
  </Tree>
</div>
```
I want to access the instance of the component ```adl-archetype-tree-leaf``` which lives inside of the <template>. I need this in order to refresh some internal icon that I need. How can I access it ? with onFocused I am getting the TreeNode so it doesnt help me much

Thank you

Edit2: I could force the component to rerender (this.archetypeService.guiTree.treeModel.update();) but thats not very optimized

**Comment by adamkleingit** [comment]
Hi,
Generally speaking in Angular, you shouldn't access elements, but change data and bind to it from the template.

But if you must, you can get the actual element of the node using `node.elementRef`, and try to locate the `adl-archetype-tree-leaf` from there.

**Comment by denkomanceski** [comment]
I know, but the idea was that the components inside the template do not subscribe to services, because we plan to have a huge tree (3MB+). Than when some change happens, I wanted to access the class instance of that component and trigger change manually. I think this will help for sure, I will try and see

Thanks
