### ISSUE TITLE
issue for drag & drop between trees

### ISSUE THREAD

**Issue by gaurav-singh-103** [500tech/angular2-tree-component#137]
Hi,
i want to drag and drop node between trees, but unable to reach out the solution, How it possible. 

I have two tree control,  one is default tree & other one is custom tree, need to create custom tree throw default tree using drag & drop concept over the node. But unable to get solution, how to move node between to trees, I have read the documentation about  angular2-tree-component. but there is no much clear to implementation for this. Please share solution as per my scenario. it's too much argent in my development

 
Please look for an answer in the docs before submitting an issue:
angular2-tree.readme.io.

In case you are reporting a bug, please specify which version of angular2-tree-component you are using.

Thank you

**Comment by adamkleingit** [comment]
Hi,
drag and drop between trees is enabled by default in the latest version.
simply set `allowDrag: true` option on both trees.
