### ISSUE TITLE
option for auto-expanding a field

### ISSUE THREAD

**Issue by seiyria** [500tech/angular2-tree-component#14]
It would be nice to be able to say "this is expanded by default" - perhaps by doing expanded: true on the object. I don't want my tree to always be collapsed by default.

**Comment by 500tech-user** [comment]
Nice feature request. I'll add it.
By default I'll call it 'isExpanded' (convention for boolean fields), and
will allow to override the field's name

On Wed, Jul 6, 2016 at 7:06 PM, Kyle J. Kemp <notifications@github.com>
wrote:

> It would be nice to be able to say "this is expanded by default" - perhaps
> by doing expanded: true on the object. I don't want my tree to always be
> collapsed by default.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/500tech/angular2-tree-component/issues/14>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACUsQ35uPkG90RG7WovIR4AqMC6PhPRTks5qS9J9gaJpZM4JGPgH>
> .
>



-- 
*Adam Klein*
*CTO & Co-Founder*
*Tel.* +972-52-747-5633
*blog.500tech.com <http://blog.500tech.com>*
meetup.com/angularjs-il

**Comment by adamkleingit** [comment]
Solved in 1.1.9. The field name is 'isExpanded'. You can change its name in the options using 'isExpandedField' field.
https://github.com/500tech/angular2-tree-component/commit/ce4a3f6bba64cb2eafb816b7f17ebe049f7bf2b6
