### ISSUE TITLE
actionMapping multi-select and drag and drop together

### ISSUE THREAD

**Issue by joshterrill** [500tech/angular2-tree-component#140]
In the docs under https://angular2-tree.readme.io/docs/options#actionmapping there's an example of how to allow multi select by clicking each of the tree nodes. This works fine. However, I'm trying to also integrate multi-select with drag and drop so that if you select 3 tree nodes, then drag them to the bottom of the tree, all 3 of them get dropped. Currently, only the node that I have my mouse on is the one that gets dropped and the other two stay in their place and remain activated. Is there a way to do this?

html:
```html
<Tree [nodes]="currentLocation" [options]="treeOptions"(onActivate)="toggleChild($event)"></Tree>
```

typescript:
```typescript
import { Component, OnInit, Inject } from '@angular/core';
import {
  TreeComponent,
  TreeNode,
  TREE_ACTIONS,
  KEYS,
  IActionMapping
} from 'angular2-tree-component';
const actionMapping:IActionMapping = {
  mouse: {
    click: TREE_ACTIONS.TOGGLE_SELECTED_MULTI
  }
};

@Component({
  selector: 'home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  
  public treeOptions = { 
    childrenField: 'Children', 
    idField: 'Oid', 
    displayField: 'FullName', 
    isExpandedField: 'expanded',
    allowDrag: true,
    levelPadding: 2,
    actionMapping
  };

  constructor() { }

  ngOnInit() {  }

  toggleChild(event) {
    console.log(event.node.data);
  }

}
```

Edit: Is there a way to access an array of currently selected nodes if you have multi-select turned on?

Edit 2: I figured out how to get the array of currently selected ones, it is stored in `event.node.treeModel.activeNodes`

Edit 3: Even when I call to `activeNodes` something strange happens... here are the steps I'm taking

1. Click one node, look at console (logging out `event.node.treeModel.activeNodes`) it shows an empty array with an arrow next to it. When I click the arrow, it expands to show Array[0] with one object in it called TreeNode. When I collapse it in the console, it goes back to saying it's an empty array. (see screenshot below)

![Imgur](http://i.imgur.com/xf9RssQ.png)
![Imgur](http://i.imgur.com/sQmn2YC.png)

2. Click another node, now the log shows an array with 1 TreeNode in it. When I expand the array in the console, it shows 2.... why is this?

![Imgur](http://i.imgur.com/cHjBlqd.png)
![Imgur](http://i.imgur.com/zWi9faE.png)

**Comment by adamkleingit** [comment]
This is a bug. The event is fired before the active nodes change. Will fix shortly

**Comment by adamkleingit** [comment]
The bug is fixed in 2.8.0.
About multi dragging - this is not currently planned, but feel free to add this functionality and make a PR.
Thanks

**Comment by joshterrill** [comment]
Okay thanks.

**Comment by svcninja** [comment]
@joshterrill 

I have 2 trees. #tree1 and #tree2. It seems I cannot get the activeNodes correctly (nodes that are multi selected)

I use this line.
`this.tree1.treeModel.activeNodes`

Do you have any suggestions?

**Comment by harishnimmala10** [comment]
Could someone please help me with the implementation of multi-select drag and drop functionality.

**Comment by joshterrill** [comment]
@harishnimmala10 It is not something that they have planned for this repo. Unless you want to write it yourself, you'll probably have to choose another library.

**Comment by harishnimmala10** [comment]
Any suggestion for the library that has this functionality?

**Comment by joshterrill** [comment]
I ended up writing an angular 2 wrapper around a jquery-based tree drag and drop library. But if you want to try another angular 2 one, try https://github.com/matthieu-D/ng2-drag-drop-tree though I have not ever used it.

**Comment by harishnimmala10** [comment]
Thnx Josh.I'll try that.

**Comment by asgharb** [comment]
@joshterrill @adamkleingit  Is there any sample code for selecting and drag multiple nodes?
