### ISSUE TITLE
loading... effect when using loadChildren method

### ISSUE THREAD

**Issue by xfilipe** [500tech/angular2-tree-component#143]
Is there some way to show that "loading..." effect when I'm calling the loadChildren method?

**Comment by adamkleingit** [comment]
Hey,
not sure what you're trying to do, but if the node is expanded and there are no children then the `loading...` shows.
So if you're trying to reload children, just make sure the node is expanded, and set its children to null.
Does that help?

**Comment by obiwan007** [comment]
I have some Problems too.
We can only request data from our backend and receive the complete tree back via redux store subscription.
If I resolve the promise in the getChildren() callback via a short delay - all is fine - but the spinner is possibly closing before the actual treedata arrived. This leads to a bit of flickering.

Do you have an example on how you could update the tree even if the promise is still ongoing?
I tried to resolve the promise within my store subscription (resolve with empty data and immediately update the tree data ) but that was not working. The spinner goes away, but no new nodes were shown.

**Comment by adamkleingit** [comment]
Hey,

You can just set the `children` attribute of the node when the data returns
from the server - that should work automatically.
Can you try that?

I should probably allow to leave the `getChildren` option empty for this
use case.


-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by adamkleingit** [comment]
Fixed in 2.8.2 - you should leave `getChildren` as empty, and update the children of the nodes when data returns from server.
@obiwan007 please reopen the issue if this does not work
