### ISSUE TITLE
webpack  AOT  v2.7  Property 'loadingTemplate' does not exist on type 'LoadingComponent'.

### ISSUE THREAD

**Issue by Jarvens** [500tech/angular2-tree-component#144]
Hi,

When i start AOT by angular-tree-component and the version  of 2.7  

throughs some mistake  like this:

`Starting compilation using the angular compiler.
Angular compilation done, starting webpack bundling.
Error: Error at /Users/kunlun/Desktop/huala-system/compiled/node_modules/angular2-tree-component/dist/components/loading.component.ngfactory.ts:40:20: Property 'loadingTemplate' does not exist on type 'LoadingComponent'.
Error at /Users/kunlun/Desktop/huala-system/compiled/node_modules/angular2-tree-component/dist/components/loading.component.ngfactory.ts:167:49: Property 'loadingTemplate' does not exist on type 'LoadingComponent'.
Error at /Users/kunlun/Desktop/huala-system/compiled/node_modules/angular2-tree-component/dist/components/loading.component.ngfactory.ts:170:44: Property 'loadingTemplate' does not exist on type 'LoadingComponent'.
Error at /Users/kunlun/Desktop/huala-system/compiled/node_modules/angular2-tree-component/dist/components/tree-node-content.component.ngfactory.ts:49:20: Property 'treeNodeContentTemplate' does not exist on type 'TreeNodeContent'.
Error at /Users/kunlun/Desktop/huala-system/compiled/node_modules/angular2-tree-component/dist/components/tree-node-content.component.ngfactory.ts:189:49: Property 'treeNodeContentTemplate' does not exist on type 'TreeNodeContent'.
Error at /Users/kunlun/Desktop/huala-system/compiled/node_modules/angular2-tree-component/dist/components/tree-node-content.component.ngfactory.ts:194:44: Property 'treeNodeContentTemplate' does not exist on type 'TreeNodeContent'.
Error at /Users/kunlun/Desktop/huala-system/compiled/node_modules/angular2-tree-component/dist/components/tree-node.component.ngfactory.ts:67:20: Property 'nodeIndex' does not exist on type 'TreeNodeComponent'.
Error at /Users/kunlun/Desktop/huala-system/compiled/node_modules/angular2-tree-component/dist/components/tree-node.component.ngfactory.ts:74:20: Property 'treeNodeContentTemplate' does not exist on type 'TreeNodeComponent'.
Error at /Users/kunlun/Desktop/huala-system/compiled/node_modules/angular2-tree-component/dist/components/tree-node.component.ngfactory.ts:81:20: Property 'loadingTemplate' does not exist on type 'TreeNodeComponent'.
`

Thank you

**Comment by Metal-Predator** [comment]
Similar situation. Though I'm getting errors only regarding TreeNodeComponent:

Property 'nodeIndex' does not exist on type 'TreeNodeComponent'
Property 'treeNodeContentTemplate' does not exist on type 'TreeNodeComponent'
Property 'loadingTemplate' does not exist on type 'TreeNodeComponent'

**Comment by Metal-Predator** [comment]
Moreover: **...\node_modules\angular2-tree-component\dist\components\tree-node.component.d.ts** really doesn't contain those props

**Comment by x0156** [comment]
Add the missing properties to the type definition file(workaround) and recompile. This should solve the issue.

**Comment by Metal-Predator** [comment]
There is also one more workaround - just take all files from lib directory, include in your project and build with your source code. Works for me.

**Comment by Jarvens** [comment]
i also solved this mistake by adding that property ,but i want find  another way

**Comment by adamkleingit** [comment]
Hey,
True, there's a weird mismatch between .d.ts and compiled.
I'll look into it

**Comment by adamkleingit** [comment]
Fixed in 2.8.0.
Please verify

**Comment by Jarvens** [comment]
thanks   i 'll have a try later
