### ISSUE TITLE
How to get routes working

### ISSUE THREAD

**Issue by xamists** [500tech/angular2-tree-component#145]
Hi. I have the following code html and I'm trying to get routes working. However, when I expand a root node, it throws an error "EXCEPTION: Cannot read property 'outlets' of null". Is there a better way to go about making so that each item in the tree menu loads a different view?

	`
	<div class="container">
	  <div class="row">
	    <div class="col-md-3">
  			<Tree #tree [nodes]="nodes" [routerLink]="[tree.treeModel.getFocusedNode()?.id]"></Tree>
  		</div> 
      <div class="col-md-9">
        <router-outlet></router-outlet>
      </div>
	  </div>
	</div>
`

**Comment by attilapapai** [comment]
Hey dude!

I don't know if we had the same issue, but this is how I achieved adding links to the tree nodes:

                    <Tree [nodes]="nodes">
                        <template #treeNodeTemplate let-node="node" let-index="index">
                            <span *ngIf="node.data.children">{{ node.data.name }}</span>
                            <a *ngIf="!node.data.children" [routerLink]="[node.data.url]">{{ node.data.name }}</a>
                        </template>
                    </Tree>

In the component:

`this.nodes = [
    {
      id: 1,
      name: 'News',
      children: [
        { id: 2, name: 'Create New', url: '/news/new' }
      ]
     }`

**Comment by adamkleingit** [comment]
@xamists  not sure what you were trying to achieve with that code.
@attilapapai 's snippet shows you how to add a custom node template with a link inside.

Thanks
