### ISSUE TITLE
Incorrect Metadata Files

### ISSUE THREAD

**Issue by vsavkin** [500tech/angular2-tree-component#147]
It seems the npm package has incorrectly generated metadata files, which means that the library does not work in the AoT mode. Just rerunning ngc fixed it.

Could you regenerate the files and publish the updated package to npm?

**Comment by ghaiat** [comment]
Hello
Any update about this one? not beeing able to use AOT is a big showstopper

**Comment by jskrzypek** [comment]
I made a pr #154 that should fix this.

**Comment by adamkleingit** [comment]
Merged, will publish a new version ASAP.
Thanks guys

**Comment by adamkleingit** [comment]
Fixed in 2.8.0.
Please verify

**Comment by ghaiat** [comment]
Yeah it works :) thanks
