### ISSUE TITLE
version 2.7.0 getNodeById doesn't use idField option...hardcoded to id: 

### ISSUE THREAD

**Issue by benharrell** [500tech/angular2-tree-component#153]
TreeModel.prototype.getNodeById = function (id) {
        return this.getNodeBy({ ## _**id: id**_ });
    };

Shouldn't this use _a[this.options.idField] ?

**Comment by adamkleingit** [comment]
True. Will be fixed today

**Comment by adamkleingit** [comment]
Wait, sorry - that's by design.
TreeNode has a getter for `id` which accesses the idField....

**Comment by benharrell** [comment]
ah thanks i see now...sorry for the wild goose chase!  :)
