### ISSUE TITLE
Please provide an example for using getNodeByPath

### ISSUE THREAD

**Issue by benharrell** [500tech/angular2-tree-component#155]
Please provide an example for using getNodeByPath, I can't find a good example and all my attempts are failing...

**Comment by adamkleingit** [comment]
There was a bug with this function if you were using a custom idField.
Will fix in coming version.

Anyway, the usage is:
`getNodeByPath([1,2,3])`

and nodes are:
```
{
  id: 1, children: [{
     id: 2,  children: [{
        id: 3 
     }]
  }]
}
```

**Comment by adamkleingit** [comment]
Closing this one, please let me know if it worked out.
Thanks

**Comment by benharrell** [comment]
i'll try tonight.  my id field is custom and is a string (guid).  so probably related to the bug you mentioned

**Comment by benharrell** [comment]
just an update.  changed the name of my field back to 'id' but using a string (guid) value...still having issues...i'll dig in some more and see what's going on.  in the meantime can you tell me the nature of the bug you fixed as it might be what's still blocking me.  

is 'id' required to be a number?
