### ISSUE TITLE
allowDrop type issue (2.8.0)

### ISSUE THREAD

**Issue by ajkyru** [500tech/angular2-tree-component#159]
node_modules/angular2-tree-component/dist/models/tree-node.model.d.ts(17,17): error TS7006: Parameter 'any' implicitly has an 'any' type.

`allowDrop: (any) => boolean;`

**Comment by adamkleingit** [comment]
Will be fixed in next version

**Comment by adamkleingit** [comment]
Fixed in 2.8.1
