### ISSUE TITLE
SystemJS import error, v2.8.0

### ISSUE THREAD

**Issue by judequinn** [500tech/angular2-tree-component#160]
Hello, I have encountered the following error while using the updated version of component: 

```
(SystemJS) XHR error (404 Not Found) loading http://localhost:8000/projects/dev/traceur↵
Error: XHR error (404 Not Found) loading http://localhost:8000/projects/dev/traceur↵	    
at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:8000/static/node_modules/zone.js/dist/zone.js:1039:29) [<root>]↵	   
 at Zone.runTask (http://localhost:8000/static/node_modules/zone.js/dist/zone.js:151:47) [<root> => <root>]↵	    
at XMLHttpRequest.ZoneTask.invoke (http://localhost:8000/static/node_modules/zone.js/dist/zone.js:345:33) [<root>]↵	
Error loading http://localhost:8000/projects/dev/traceur↵	
Unable to load transpiler to transpile http://localhost:8000/static/node_modules/angular2-tree-component/dist/angular2-tree-component.js↵	
Error loading http://localhost:8000/static/node_modules/angular2-tree-component/dist/angular2-tree-component.js as "angular2-tree-component" from http://localhost:8000/static/projects/src/app.module.js
```

Previous version (2.7.0) works perfectly fine.

angular2-tree-component: v2.8.0
@angular: v2.4.4

**Comment by coopernyc** [comment]
Same issue with new 2.8.0 version, 2.7.0 works fine
"(SystemJS) XHR error loading file:///C:/_projects/CoreElectron/build/traceur.js
	Error: XHR error loading file:///C:/_projects/CoreElectron/build/traceur.js
	    at new Error (native)
	    at Zone.runTask (file:///C:/_projects/CoreElectron/node_modules/zone.js/dist/zone.js:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (file:///C:/_projects/CoreElectron/node_modules/zone.js/dist/zone.js:345:33) [<root>]
	Error loading file:///C:/_projects/CoreElectron/build/traceur.js
	Unable to load transpiler to transpile file:///C:/_projects/CoreElectron/node_modules/angular2-tree-component/dist/angular2-tree-component.js
	Error loading file:///C:/_projects/CoreElectron/node_modules/angular2-tree-component/dist/angular2-tree-component.js as "angular2-tree-component" from ...

**Comment by arooran** [comment]
Having the same problem once I installed the 2.8.0 version. Tried to downgrade to 2.7.0 still having some compilation issues. Looking for the solution

**Comment by adamkleingit** [comment]
I'll look into it.
Can you paste your package.json here?

**Comment by adamkleingit** [comment]
I'm not having these errors using angular-cli. It would help if you send a link to your repo and configuration. Thanks

**Comment by judequinn** [comment]
We use systemJS in development and the error seems to occur due to ES6 module format used in js files of angular2-tree-component v.2.8.0. As of v. 2.7.0 everything was in commonjs and didn't cause any problems for systemJS. Is there any chance that you would return to commonjs format?

Relevant parts of configuration:
SystemJS config
```    
map: {
      'app': '/static/project/src/',
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      'rxjs': 'npm:rxjs',
      'angular2-tree-component':    'npm:angular2-tree-component',
      'lodash':                     'npm:lodash'
    },
    packages: {
      'app':                       { main: 'main.js', defaultExtension: 'js' },
      'rxjs':                      { defaultExtension: 'js' },
      'angular2-tree-component':   { main: 'dist/angular2-tree-component.js', defaultExtension: 'js' },
      'lodash':                    { main: 'lodash.js', defaultExtension: 'js' }
    }
```

package.json: 
```
  "dependencies": {
    "@angular/common": "^2.4.4",
    "@angular/compiler": "^2.4.4",
    "@angular/core": "^2.4.4",
    "@angular/forms": "^2.4.4",
    "@angular/http": "^2.4.4",
    "@angular/platform-browser": "^2.4.4",
    "@angular/platform-browser-dynamic": "^2.4.4",
    "@angular/router": "^3.4.4",
    "angular2-ie9-shims": "0.0.2",
    "angular2-tree-component": "git+https://git@github.com/judequinn/angular2-tree-component.git",
    "core-js": "^2.4.1",
    "lodash": "^4.17.4",
    "rxjs": "^5.0.3",
    "systemjs": "^0.19.43",
    "zone.js": "^0.7.6"
  },
```
app.module.ts: 
```
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { BrowserModule } from '@angular/platform-browser';

import { AppComponent } from './components/components';
import { TreeModule } from 'angular2-tree-component';

@NgModule({
  imports:      [ BrowserModule, HttpModule, FormsModule, TreeModule ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})

export class AppModule {  }
```

**Comment by judequinn** [comment]
It seems that there's some issue with SystemJS and es2015 modules that are not imported correctly. Has anyone else tried to use v2.8.0 with SystemJS and maybe found a solution?

@adamkleingit unfortunately we don't use angular-cli and just bundle our app with SystemJS in development mode. SystemJS version is 0.19.46.

**Comment by adamkleingit** [comment]
I'm working on building a UMD module. In the meantime - you can fork the repo and change the tsconfig to build ES5 files

**Comment by chuihinwai** [comment]
cef0aad (2.8.1) is now working with the following `map` for SystemJS, no entry in `packages` required. I would consider this closed. Thanks @adamkleingit!

```
map: {
  // angular bundles
  '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
  …
  'angular2-tree-component': 'node_modules/angular2-tree-component/dist/angular2-tree-component.umd.js',
  …
}
```

**Comment by judequinn** [comment]
@adamkleingit thanks a lot, closing the issue.

**Comment by adamkleingit** [comment]
No problem.
I'm not using SystemJS myself. Is there anything I can do to make it
clearer on how to use it with SystemJS or make it easier to use?

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by govindmahecha** [comment]
@coopernyc Thanks , It works for me
