### ISSUE TITLE
How to enable multiselect?

### ISSUE THREAD

**Issue by chrissteinmeyer** [500tech/angular2-tree-component#169]
Hi,

I looked through your documentation and tried the component a bit but I didn't find any clue how to achieve multiselect without take a deep dive into the component sources. How I can enable it so that the user can just single click some nodes to select them or isn't that possible?

Best Regards

**Comment by oudinia** [comment]
Hello Chris,

From the demo, it says you can shift click to select multiple nodes.

I tested and it works on the demo app.

Cheers

**Comment by chrissteinmeyer** [comment]
Big thanks! You're right this works in the demo, somehow I didn't recognized it..
So I can look into it and enable this for single mouse click! :)
