### ISSUE TITLE
Need help overriding styles

### ISSUE THREAD

**Issue by adrian-mitangi** [500tech/angular2-tree-component#171]
Hi,

I'm trying to override some of the tree styles, like I tried adding:

<style type="text/css">
  .tree  {
   cursor: default !important;
  }

  .tree .node-content-wrapper {
    cursor: default !important;
  }
</style>

to my component template.  But it's not working.

Any suggestions on how to override tree styles?

**Comment by adamkleingit** [comment]
Hey,
no reason it shouldn't work, I'm using ViewEncapsulation.None everywhere.
Can you share your code?

**Comment by adrian-mitangi** [comment]
<style type="text/css">
  .title {
    margin: 15px;
  }

  .metatree  {
    font-size: 14px;
  }

  .metatree .node-content-wrapper {
    cursor: auto !important;
  }

  
</style>

<table class="doc-table table table-bordered">
  <tr>
    <td>
      <h5 class="title text-center">
        Organizational Metadata Tree
      </h5>

      <Tree #tree
            class="metatree"
            [nodes]="nodes"
            [options]="customTemplateStringOptions"
            (onActivate)="selectNode($event)"
            (onDeactivate)="deselectNode($event)">
        <template #treeNodeTemplate let-node>
          <node [node]="node"
                (createChildNode)="addChildNode($event)"
                (deleteChildNode)="deleteNode($event)"></node>
        </template>
      </Tree>
    </td>

    <td>
      <selected-metadata [selectedMetadata]="selectedNode">
      </selected-metadata>
    </td>

    <td>
      <files></files>
    </td>

  </tr>
</table>

**Comment by adamkleingit** [comment]
Hey, you should add styles to your component using the `styles` attribute,
not using <style> tags in the component template.
Can you try that and see if the problem persists?

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by adamkleingit** [comment]
@adrian-mitangi any news?

**Comment by adrian-mitangi** [comment]
Hi,

I'll give it a try today and report back to you.  Thanks for following up.

Adrian

**Comment by adamkleingit** [comment]
Awesome. I'll close the issue and if it doesn't work let me know
