### ISSUE TITLE
Cannot read

### ISSUE THREAD

**Issue by theS3ns** [500tech/angular2-tree-component#178]
Hi,
`import { Component, ViewChild } from '@angular/core';
import { TreeModule, TreeComponent, TreeNode, TreeModel } from 'angular2-tree-component';
import * as _ from 'lodash';

@Component({
  selector: 'obtree',
  styleUrls: ['./obtree.component.scss'],
  templateUrl: './obtree.component.html'
})
export class ObTreeComponent {

  @ViewChild(TreeComponent)
  private _tree:          TreeComponent;
  private _nodes:         TreeNode[] = [];
  private _node:          any = {};
  constructor(){
    this._node = { uid: 1, name: 'everything' };
    if (this._nodes) {
      this._nodes.push(this._node)
    }
  }

  addNode(node) {
    node[0].children.push(this._node) ;
    this._tree.treeModel.update();
  }
}`
 Cannot read property 'children' of undefined or  Cannot read property '0' of undefined or  Cannot read property 'push' of undefined

I do not understand where the problem is.

**Comment by obiwan007** [comment]
Maxbe check if children is defined as an Array first before you pus via addNode.
If the Array is not initialized then create one first:
if (!node[0].children){
    node[0].children=[];
}
node[0].children.push(this._node) ;

**Comment by adamkleingit** [comment]
Hi,
this looks like a bug in your code, not in the library.
Also, why are you holding an array of TreeNode's? And you are pushing a plain object to it, which is not a TreeNode....

Closing the issue.
