### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by DivyaDDev** [500tech/angular2-tree-component#186]
Please help me use the COntext Menu. I have no documentation regarding it. I want to include "Add" and link it to a function add() when you right click on tree node.

**Comment by adamkleingit** [comment]
Hey,
you have 2 options:
override actionMapping.mouse.contextMenu
provide a custom template that has a contextMenu

See
[https://angular2-tree.readme.io/docs/action-mapping](https://angular2-tree.readme.io/docs/action-mapping)
[https://angular2-tree.readme.io/docs/templates](https://angular2-tree.readme.io/docs/templates)

For more information

**Comment by sagarpatel-byteparity** [comment]
can anyone share example of integration of context menu with tree? so i can get better idea because documentation doesn't better approach at my view.

**Comment by zbeedatm** [comment]
Same for me.
I had choosen the first option: [https://angular2-tree.readme.io/docs/action-mapping](https://angular2-tree.readme.io/docs/action-mapping)

`const actionMapping:IActionMapping = {
      mouse: {
        contextMenu: (tree, node, $event) => {
          $event.preventDefault();
          alert(`context menu for ${node.data.name}`);
        }
      }
};`

and now I need to show some menu items when clicking right click on the node.
How to accomplish that?

**Comment by arcdream** [comment]
zbeedatm
have you been able to achieve the context menu on tree? thanks

**Comment by quantotto** [comment]
If this is of interest for someone, you can leverage the ngx-contextmenu component:
`npm install --save ngx-contextmenu @angular/cdk`

Then follow the example to set it up in your Angular app: https://stackblitz.com/edit/ngx-contextmenu-example

As for applying it to tree, use the template method. For example (assuming your node data contains 'name' property. Note that showMessage is a method of your component containing tree.
```
<tree-root
      [nodes]="tree"
      [options]="options"
>
  <ng-template #treeNodeTemplate let-node let-index="index">
    <span [contextMenu]="basicMenu" [contextMenuSubject]="node.data">
      {{ node.data.name }}
    </span>
  </ng-template>
</tree-root>
<context-menu>
  <ng-template contextMenuItem (execute)="showMessage('Hi, ' + $event.item.name)">
    Say hi!
  </ng-template>
  <ng-template contextMenuItem divider="true"></ng-template>
  <ng-template contextMenuItem let-item (execute)="showMessage($event.item.name + ' said: ' + $event.item.id)">
    Bye, {{item?.name}}
  </ng-template>
</context-menu>
```

**Comment by Js4Life** [comment]
any updates?
