### ISSUE TITLE
SystemJS - Unable to dynamically transpile ES module

### ISSUE THREAD

**Issue by ajkyru** [500tech/angular2-tree-component#189]
Release 2.8.2
Error: Unable to dynamically transpile ES module A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`.

**Comment by adamkleingit** [comment]
Hey, can you try configuring systemJS to look at the UMD bundle?
'angular2-tree-component': 'node_modules/angular2-tree-component/dist/angular2-tree-component.umd.js',

see #187

**Comment by adamkleingit** [comment]
Updated the docs
