### ISSUE TITLE
Ability to configure keyboard navigation keys

### ISSUE THREAD

**Issue by forforeach** [500tech/angular2-tree-component#19]
Hi,

In the current implementation of the tree it is possible to select/deselect a node with keyboard, pressing on enter/space. I have a requirement to implement tree node template with text input that allows spaces. Default behavior of enter/space is prevented, so it is impossible to use space inside node template.

I suggest to allow configuration of keyboard navigation keys through options object.

Thanks

**Comment by adamkleingit** [comment]
Hey,
I'm actually already working on this at the moment. Hope to release soon.

Cheers

**Comment by adamkleingit** [comment]
Just released a new version - 1.1.13 with action mappings:
https://angular2-tree.readme.io/v1.1.13/docs/action-mapping

You can do this to cancel the action on `spacebar` key:
```
import { TREE_ACTIONS, KEYS } from 'angular2-tree-component';

actionMapping: {
  keys: {
    [KEYS.SPACE]: null
  }
}
```

**Comment by adamkleingit** [comment]
@forforeach - can you verify so I can close the issue?

**Comment by forforeach** [comment]
Sorry, I'm far from my computer and won't be able to verify it until end of month. Thanks for quick update of the component.

**Comment by adamkleingit** [comment]
OK I'll close and if it's still a problem we can reopen
