### ISSUE TITLE
Getting async mode running (error Cannot read property '_id' on string 'Aktiv')

### ISSUE THREAD

**Issue by mfechner** [500tech/angular2-tree-component#190]
Dear all,

I'm not sure if this is the right place to ask for help, as this question is not an issue, but a try to get help.

I have problems understanding how to feed data into angular2-tree-component to get async loading working correctly.
The complete sample code can be found here: https://github.com/mfechner/meteor-ng2-tree/tree/angular2-tree-component

My tree is stored in a mongo database and the structure is the following:
`{ _id: string, children: string[]}`

An example to have two nodes:
`{_id: 'ROOT_NODE', children: ['Aktiv', 'Passiv']}`
`{_id: 'Aktiv', children: []}`
`{_id: 'Passiv', children: []}`

The string Aktiv in children on ROOT_NODE is pointing to the next _id. So to display it I must fetch the next record with _id='Aktiv' and so on. That is what I understood the task of getChildren (please see file client/imports/app/app.component.ts).

As my fields do not match the standard names I use options also to set idField and displayField.

But I have problems to get it working.
I see the error message:
`Exception in queued task: Error: Error in ./AppComponent class AppComponent - inline template:6:83 caused by: Cannot create property '_id' on string 'Aktiv'`

Has anyone an idea what is wrong here?

Thanks a lot.

**Comment by adamkleingit** [comment]
Hey,

You cannot pass an array of strings in `children` attribute - the tree tries to use that field as a list of child nodes (objects).

So either change the data structure and rename `children` (to something like `childrenIds`),
Or specify a different `childrenField` in options (like `childNodes`).

Also, you need to add `hasChildren: true` to all nodes that have children:
```
{_id: 'ROOT_NODE', hasChildren: true, childrenIds: ['Aktiv', 'Passiv']}
```
