### ISSUE TITLE
isExpanded not working

### ISSUE THREAD

**Issue by adrian-mitangi** [500tech/angular2-tree-component#193]
I have a tree data structure where I'm setting the "isExpanded" to true for nodes that have child nodes.  But The tree component still renders the nodes in closed state.

**Comment by adamkleingit** [comment]
Hi,

isExpanded is only for initial render. If you want to expand / collapse nodes after the tree is rendered please use the methods `expand` or `collapse` on the treeNode.

**Comment by jcimoch** [comment]
@adamkleingit 
How to detect moment when treeModel.expandAll can be executed? In my case I want to expand new data which is async. If i call this method before tree component finishes build I got 
```
ypeError: Cannot read property 'forEach' of undefined
    at TreeModel.webpackJsonp.../../../../angular-tree-component/dist/models/tree.model.js.TreeModel.expandAll
```
