### ISSUE TITLE
Expand one node and collapse the others ?

### ISSUE THREAD

**Issue by vptcnt** [500tech/angular2-tree-component#194]
Hi,

is it possible to collapse all the expanded nodes before  expanding a new node ?
It will allow to act like an Accordion...

Thanks
Vincent

**Comment by adamkleingit** [comment]
Hi,

You can override the `actionMapping.mouse.expanderClick` option with your own handler,
and call `collapseAll` method on the treeModel before calling TREE_ACTIONS.TOGGLE_EXPANDED.

All the best

**Comment by chandrn** [comment]
I tried this, it works for the top level nodes, but not the child nodes. On expanding child nodes, the whole tree collapses, nothing expands.

I have a stackblitz setup here: https://stackblitz.com/edit/angular-tree-component-u3gmlp-pt3rcw?file=app%2Ffulltree%2Ffulltree.component.ts

You can check the child2.2 under root2

Not sure if I'm missing something.
