### ISSUE TITLE
Expanded tree nodes doesn't work after first time 

### ISSUE THREAD

**Issue by MahmoudMohsen1990** [500tech/angular2-tree-component#202]
Hi Team,

I would like to thank you for your great component and kindly know that I have an issue when trying to load dynamic nodes [asyc calls ] , it works first time but second , it returns all records collapsed however it has a child and isExpanded is true 

and there's my code 

HTML :
       <Tree #tree2 [nodes]="nodes2">
               //  template and so on like mentioned at documentations 
            </Tree>
TS 

  @ViewChild('tree') public tree: any;

search:void(){
let newListFromServer=GetData();  -- > complete tree with children and isexpanded=true
nodes=newListFromServer;
}

I'm using version "angular2-tree-component": "^2.8.1",

any advice

**Comment by adamkleingit** [comment]
Hi,
isExpanded only works for the first rendering of the tree.
You can wrap the tree with ngIf and destroy + re-render it when doing server calls to overcome this.

Also, isExpanded will soon be removed.

**Comment by MahmoudMohsen1990** [comment]
thank you so much but how can I destroy and re render the tree ? just give me hint
