### ISSUE TITLE
Reliability, and `toggle() is deprecated, please use toggleExpanded()`

### ISSUE THREAD

**Issue by Tahler** [500tech/angular2-tree-component#24]
I notice the expansion of nodes can be rather unreliable (sometimes clicking does nothing), and this warning pops up in the console when it actually does expand: 
`toggle() is deprecated, please use toggleExpanded()`

Your demo does not have the reliability issue, but does still throw that warning up in the console.

I am using System.js if that makes a difference for this issue.

**Comment by adamkleingit** [comment]
Which version are u using? I noticed the click problem, need to investigate.
Probably something with the click area.
Have u tried to investigate it yourself?

About deprecated - I'll check, but that won't affect the libraries
behaviour anyway

**Comment by Tahler** [comment]
It is the current version off NPM (1.1.12).
I looked very briefly at the template `(click)` binding to the arrow, but that was it. I am on somewhat of a time crunch on some other things so I did not dive deep into the code here.

**Comment by adamkleingit** [comment]
Fixed in 1.1.14
