### ISSUE TITLE
Feature - allow configuring indentation

### ISSUE THREAD

**Issue by adamkleingit** [500tech/angular2-tree-component#26]
Need to support these options:
- children padding - default
  - allow to supply a method that returns the children padding for each node
- per node padding
  - calculated by default as X \* node.level
  - allow to override X
  - allow to supply a method that returns the padding for each node

**Comment by johnking** [comment]
Like the options suggested above! @adamkleingit

**Comment by adamkleingit** [comment]
Added in 2.4.0
