### ISSUE TITLE
Update for rc5 - NgModules

### ISSUE THREAD

**Issue by Gillardo** [500tech/angular2-tree-component#36]
Any plans on when is this component going to be updated to support rc5 and ngModules?

**Comment by aramin** [comment]
Please merge https://github.com/500tech/angular2-tree-component/pull/29 so we can use the tree component in rc6 where no directives within a component are allowed anymore.

**Comment by isaacplmann** [comment]
I closed #29 because it wasn't relevant.  But I've create #43 which addresses this issue.

**Comment by adamkleingit** [comment]
Solved in 1.2.0 #43
