### ISSUE TITLE
active async load

### ISSUE THREAD

**Issue by sante85** [500tech/angular2-tree-component#37]
how to active async load??

THANKS

**Comment by adamkleingit** [comment]
Hi,
Please write more descriptive messages, I don't really understand what you
mean.
Thanks

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633
