### ISSUE TITLE
Title is displayed twice

### ISSUE THREAD

**Issue by aramin** [500tech/angular2-tree-component#4]
I encountered the problem, that the title field (displayField) is rendered twice. Same behaviour can be seen in your demo:
![image](https://cloud.githubusercontent.com/assets/7523087/16091980/4c657cb2-3336-11e6-88d8-67a089520bb1.png)

Bug or Feature? :smile:

**Comment by isaacplmann** [comment]
I saw this too.  I believe this is fixed by PR #2.

**Comment by adamkleingit** [comment]
Solved by: #2
