### ISSUE TITLE
Update to angular 2 rc.6

### ISSUE THREAD

**Issue by nicolae536** [500tech/angular2-tree-component#41]
Can you please update the tree component to the last angular rc ?

**Comment by adamkleingit** [comment]
Will do. Hopefully this weekend

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by nicolae536** [comment]
Great thanks :D

**Comment by isaacplmann** [comment]
I'm working on a pull request that will update to RC6.  I'm finding that the AdHoc component strategy isn't going to work with AoT compilation.  I'm close to a solution using <template> tags in the content of the component that will keep all the functionality and allow for AoT compilation - but existing code will need to move template strings out of the options object and into the <template> tag(s).

**Comment by isaacplmann** [comment]
#43 is the pull request I mentioned.

**Comment by adamkleingit** [comment]
Fixed in #43
