### ISSUE TITLE
onDeactivate event doesn't fire when another node is activated

### ISSUE THREAD

**Issue by isaacplmann** [500tech/angular2-tree-component#45]
If you activate a node and then activate a different node without multiselect, there is no onDeactivate event fired for the first node.  This basically forces you to maintain your own list of selected nodes instead of relying on the tree to handle it for you.

I'd submit a PR, but I want to wait until you decide what to do with #43.

**Comment by isaacplmann** [comment]
The more I think about this, more I think this is at least partially a documentation issue.  I'm not sure what onDeactivate, onActivate and onActiveChanged actually mean.  Is this behaving the way you intended it to?

## How I thought it would work
My initial assumption, just from looking at the names, is this:
- onActivate: fires any time a node goes from not active to active
- onDeactivate: fires any time a node goes from active to not active
- onActiveChanged: fires any time a node changes active state in either direction

### So a test case would go like this:
#### 1. Node1 clicked
- onActivate(Node1)
- onActiveChanged(Node1, true)

#### 2. Node2 clicked
- onDeactivate(Node1)
- onActiveChanged(Node1, false)
- onActivate(Node2)
- onActiveChanged(Node2, true)

#### 3. Node1 shift-clicked (to multi select)
- onActivate(Node1)
- onActiveChanged(Node1, true)

#### 4. Node3 clicked (back to single select)
- onDeactivate(Node1)
- onActiveChanged(Node1, false)
- onDeactivate(Node2)
- onActiveChanged(Node2, false)
- onActivate(Node3)
- onActiveChanged(Node3, true)

#### 5. Node3 clicked (to deselect)
- onActiveChanged(Node3, false)
- onDeactivate(Node3)

## How it currently works
- onActivate: fires any time a node goes from not active to active
- onDeactivate: fires when a node is explicitly clicked to deactivate it (not when clicking another node)
- onActiveChanged: fires only when a node has active state toggled

### The same test case:
#### 1. Node1 clicked
- onActiveChanged(Node1, true)
- onActivate(Node1)

#### 2. Node2 clicked
- onActiveChanged(Node2, true)
- onActivate(Node2)

#### 3. Node1 shift-clicked (to multi select)
- onActiveChanged(Node1, true)
- onActivate(Node1)

#### 4. Node3 clicked (back to single select)
- onActiveChanged(Node3, true)
- onActivate(Node3)

#### 5. Node3 clicked (to deselect)
- onActiveChanged(Node3, false)
- onDeactivate(Node3)

**Comment by adamkleingit** [comment]
Fixing....

**Comment by adamkleingit** [comment]
Fixed in 1.2.2
