### ISSUE TITLE
Internet Explorer error - works in chrome / firefox

### ISSUE THREAD

**Issue by carmenbranje** [500tech/angular2-tree-component#46]
I am getting this in the console of IE when I try and use angular2-tree-component. 

HTML1300: Navigation occurred.
localhost:64766
Error: XHR error (404 Not Found) loading http://localhost:64766/angular2-tree-component
	Error loading http://localhost:64766/angular2-tree-component as "angular2-tree-component" from http://localhost:64766/app/coaching-planner/coaching-planner.component.js

Chrome and Firefox are not throwing errors.

**Comment by adamkleingit** [comment]
Hi,
are you using webpack or systemjs?
Can you share your code?


-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by adamkleingit** [comment]
Hey, any updates?
