### ISSUE TITLE
Is its possible to focus multiple nodes

### ISSUE THREAD

**Issue by carmenbranje** [500tech/angular2-tree-component#47]
I'd like to filter the nodes, and focus all the nodes that satisfy the filter. Is that possible to do?

**Comment by adamkleingit** [comment]
Hi,
when you say focus, what do you mean?

Currently filtering marks all nodes that match the filter and their
ancestors with isHidden = false, and all the rest with isHidden = true.
You can always traverse the tree and call `focus` / `toggleActivated` /
`expand` / `scrollIntoView` on whatever node you wish.


-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by carmenbranje** [comment]
The filtering is removing the unmarked nodes, but not showing the marked nodes. So lets say I have 3 levels to my tree, and the root node is closed. If I do a filter and the search finds a hit on a node at level 3, the tree isn't expanded to show that node. I have to go expand the root node, and then the level 2 node to see the level 3 node that was hit in the search.

**Comment by adamkleingit** [comment]
OK, I can add a flag that will tell the tree to make sure all nodes are
visible after filtering

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by carmenbranje** [comment]
That would be pretty amazing. Thank you!

**Comment by carmenbranje** [comment]
Wondering if this was implemented in the latest versions?

**Comment by adamkleingit** [comment]
Adding it now....

**Comment by adamkleingit** [comment]
Fixed in 1.2.2

**Comment by abmg84** [comment]
Hi,

Please could you explain me how to filter the tree by holding all the nodes visible? I don't know if it's possible, but I need to expand the nodes that correspond with the searching value and mark this with some css styles.
