### ISSUE TITLE
Move from "typings" to "@types/XXX"

### ISSUE THREAD

**Issue by shlomiassaf** [500tech/angular2-tree-component#48]
The current setup will error when the local system does not have the `typings` global module.

There is a post install script that runs `typings`.

Since `typings` is fading away and `@types` is the de facto solution for type definition, maintained by MS I suggest moving to it.

**Comment by adamkleingit** [comment]
It shouldn't error because typings is a dependency, so npm should run it from node_modules/.bin.
@types is only supported in Typescript 2.0, no?
Do you know how I add this library to the @types repository?

**Comment by shlomiassaf** [comment]
@adamkleingit I don't think you need to, the bundle comes with `.d.ts` files so there's no need.

BTW, angular now uses Typescript 2.0 so you should too, from my past experience there's nothing to change in your code unless you want to use some new flags

**Comment by shlomiassaf** [comment]
as for the issue, it only worked after I `npm install typings -g` but maybe it's something local in my setup

**Comment by adamkleingit** [comment]
I'll look into it

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by ciesielskico** [comment]
Same error, cannot install due to missing typings.json

**Comment by ghaiat** [comment]
same here

**Comment by isaacplmann** [comment]
I'm running into this issue too.  Working on a fix.

**Comment by ciesielskico** [comment]
I forked this repo, removed postinstall from package.json, and it works.

**Comment by isaacplmann** [comment]
@ciesielskico want to submit a PR?  That will make it easier for @adamkleingit to just click a button and accept the change.

**Comment by ciesielskico** [comment]
Here you go
https://github.com/500tech/angular2-tree-component/pull/57

**Comment by isaacplmann** [comment]
Here's a workaround for people not wanting to clone and npm link the repo:

Create a blank `typings.json` file in the root of your project directory.

**Comment by adamkleingit** [comment]
Solved in 2.1.0
#62
