### ISSUE TITLE
Remove the lodash dependency

### ISSUE THREAD

**Issue by shlomiassaf** [500tech/angular2-tree-component#49]
Since this is a library, forcing the user to use `lodash` is a problem.

In [here](https://github.com/500tech/angular2-tree-component/blob/master/lib/components/tree.component.ts#L8) there is a direct import of the whole `lodash` library.

It should be either removed and functionality should be manually written,.
Or, only required functions from `lodash` should be imported.

**Comment by adamkleingit** [comment]
Yeah, this is known. Especially a problem with SystemJS. Refers to #6 
Need to take lodash out of node_modules library so that it is bundled together with angular2-tree-component, and require only the specific functions.

**Comment by shlomiassaf** [comment]
There's no need to remove it from the `node_modules` directory, it should be part of the modules for development (in `package.json`)

Just make sure it's the latest `lodash` (4+).
You can easily import specific modules, for example:
```
require('lodash/forEach');
```

I like to wrap them in my own module so I can swap things later on:
```ts
export const forEach: typeof _.forEach = require('lodash/forEach');
export const extend: typeof _.extend = require('lodash/extend');
export const merge: typeof _.merge = require('lodash/merge');
export const assign: typeof _.assign = require('lodash/assign');
export const defaults: typeof _.defaults = require('lodash/defaults');
```

> The `lodash` types must be loaded for `typeof _.forEach` to work

**Comment by adamkleingit** [comment]
I usually just import what I need as such:
import { merge, extend } from 'lodash';

But currently node_modules are excluded from tsc compilation - which means
that lodash methods are excluded from the bundle,
which means that lodash must be a dependency of whoever uses
angular2-tree-component.

If I bundle everything with rollup it should be fine I guess (then I can
put it as a devDependency).

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by shlomiassaf** [comment]
@adamkleingit I think it should work with rollup, didn't test it though. If it resolves modules the node way then it should,

**Comment by chuihinwai** [comment]
Existing project uses _underscore.js_, Lodash is overriding the `_`, what options do I have?

**Comment by adamkleingit** [comment]
I will bundle the lodash methods inside the module

**Comment by chuihinwai** [comment]
@adamkleingit I tried copying the `node_modules/lodash` folder into `angular2-tree-component/dist`, is that how bundling works?

**Comment by adamkleingit** [comment]
Actually what you are describing is weird. It shouldn't expose _ as a global variable anyway.
Can you share a link to your code?

**Comment by chuihinwai** [comment]
I have solved the problem by calling _lodash.js_'s `noConflict()` in `main.ts`. The Global variable `_` is then returned to _underscore.js_. Thanks!
```
platformBrowserDynamic().bootstrapModule(AppModule);
…
_.noConflict();
```

**Comment by adamkleingit** [comment]
Hey,
I'm currently bundling the lodash's methods that the tree uses inside the UMD bundle (dist/angular2-tree-component.umd.js).
This bundle should be loaded when using SystemJS.
I believe it also hides the global `_` variable.
