### ISSUE TITLE
Clicking on Parent node does not change the icon to down arrow

### ISSUE THREAD

**Issue by anubrato** [500tech/angular2-tree-component#50]
I am using angular2-tree-component with webpack and all the functionality works just fine. The only issue I see is that if I click on a parent node that has one or more children, the icon of the parent node does not change to the down arrow when the parent node is in expanded state.
From what I can see I dont need to add any CSS files, it should just work. What am I missing?
Thanks.

**Comment by adamkleingit** [comment]
Which version are you using? This was fixed in 1.1.15

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by anubrato** [comment]
Apologies, I forgot to mention that I am using 1.1.14. I shall upgrade and check. Thanks!

**Comment by adamkleingit** [comment]
Cool 👍
