### ISSUE TITLE
1.2.0 published to npm

### ISSUE THREAD

**Issue by Gillardo** [500tech/angular2-tree-component#52]
Can you publish it to npm please..... Ta

**Comment by lzoubek** [comment]
I'd be also happy to consume 1.2..0 from npmjs

**Comment by Gillardo** [comment]
#53

**Comment by tscislo** [comment]
I can still see 1.1.18 version on npm. Can you please publish the new version?

**Comment by ciesielskico** [comment]
1.2.0 publish would be much appreciated, thanks!

**Comment by adamkleingit** [comment]
Hi, just published version 1.2.0 - please update and check again.

Thanks
