### ISSUE TITLE
Upgraded to Angular 2.0.0, binding problems now

### ISSUE THREAD

**Issue by carmenbranje** [500tech/angular2-tree-component#55]
Hi

I'm getting this error after upgrading to Angular 2.0.0.

zone.js@0.6.23?main=browser:344 Unhandled Promise rejection: Template parse errors:
Can't bind to 'nodes' since it isn't a known property of 'Tree'. ("<Tree #tree 
                          [ERROR ->][nodes]="nodes" 
                          [focused]="true" 
                          [options]="o"): CoachingPlannerComponent@9:26

This used to work before I upgrade, and I haven't changed anything else.

This is my template code. 
` <Tree #tree 
  [nodes]="nodes" 
  [focused]="true" 
  [options]="options">        
</Tree>`

`import { Component, NgModule } from '@angular/core';
import { Router } from '@angular/router';
import { TreeComponent } from 'angular2-tree-component';

@Component({
    selector: 'coaching-planner',
  
    templateUrl: 'app/coaching-planner/coaching-planner.component.html',
    styleUrls: ['app/coaching-planner/coaching-planner.component.css']
})

@NgModule({
        declarations: [TreeComponent]
})

export class CoachingPlannerComponent{
   
    data: any = "DELETE FOR EXAMPLE THIS WORK BEFORE THOUGH"
    nodes: any = [];

    constructor(private router: Router) {

    }

    ngOnInit(): void {

      
        this.nodes = JSON.parse(this.data);

        
    }
    myFilterNodes(): void  {
        TreeComponent
        console.log("hey!!!!!!!!!!!");

    }
    gotoDetail(): void {

    }

    

}
`

Thanks,
Carmen

**Comment by adamkleingit** [comment]
Which version of angular2-tree-component are you using?
Are you using the tree as an NgModule?
Can you send link to your code?



-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by carmenbranje** [comment]
Hey Adam

Thanks for your reply!

I am using 1.1.18

Not too certain what you mean by using it as an NgModule. Do you mean using 

@NgModule({
declarations: [TreeComponent]
})

Because I am doing that. 

I am just working locally at moment so I can't easily post my code other than what I posted above.

**Comment by Gillardo** [comment]
this is another reason we need 1.2.0 up on npm.....  Any news?

**Comment by adamkleingit** [comment]
Hi, just published version 1.2.0 - please update and check again.

Thanks
