### ISSUE TITLE
Upgraded to 1.2.1 still can't bind

### ISSUE THREAD

**Issue by carmenbranje** [500tech/angular2-tree-component#59]
I still get this:

Can't bind to 'nodes' since it isn't a known property of 'Tree'. ("
                    
                    <Tree #tree 
                          [ERROR ->][nodes]="nodes" 
                          >

<page-header [title]="'Coaching Planner'"></page-header>

    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">User Selection</div>
                <div class="panel-body tree-container" style="overflow-y:auto;">
                    
                    <Tree #tree 
                          [nodes]="nodes" 
                          >
                         
                    </Tree>
                    <button (click)="tree.treeModel.filterNodes('Derek');">next node</button>
                    <div class="form-group" id="select-preset">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">Pre-defined Reports</div>
                <div class="panel-body">
                    <div class="form-group" id="select-preset">
                        Select Preset Reports (optional)
                        <select class="form-control" id="selectpreset">
                            <option value="" disabled selected>Select your report preset</option>
                            <option aria-label="All Stars">All Stars</option>
                            <option>Business By Section</option>
                            <option>Business By Product</option>
                            <option>Advisor Pass or Fail</option>
                            <option>Staff Listing</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
</div>

import { Component, NgModule } from '@angular/core';
import { Router } from '@angular/router';
import { TreeComponent } from 'angular2-tree-component';

@Component({
    selector: 'coaching-planner',
  
    templateUrl: 'app/coaching-planner/coaching-planner.component.html',
    styleUrls: ['app/coaching-planner/coaching-planner.component.css']
})

@NgModule({
        imports: [TreeComponent]
})

export class CoachingPlannerComponent{
    data = "[{\"name\":\"Jared Gould\",\"...............
    
    nodes: any = [];

    constructor(private router: Router) {

    }

    ngOnInit(): void {

      
        this.nodes = JSON.parse(this.data);

        
    }
    myFilterNodes(): void  {
        TreeComponent
        console.log("hey!!!!!!!!!!!");

    }
    gotoDetail(): void {

    }

    

}

**Comment by isaacplmann** [comment]
you need to import `TreeModule` from angular2-tree-component and change your NgModule like this:

```js
@NgModule({
imports:[TreeModule]
})
export class AppModule {}
```

See the [Angular 2 documentation on using NgModule](https://angular.io/docs/ts/latest/guide/ngmodule.html) for more information.

**Comment by carmenbranje** [comment]
Made the change, still receiving the error.

**Comment by isaacplmann** [comment]
The `TreeModule` is not being imported correctly into your application.  Look at the [webpack](https://github.com/500tech/angular2-tree-component/blob/master/example/webpack/src/app) example to see how you can import the module correctly.  I think the [app.module.ts](https://github.com/500tech/angular2-tree-component/blob/master/example/webpack/src/app/app.module.ts) file and the [app.component.ts](https://github.com/500tech/angular2-tree-component/blob/master/example/webpack/src/app/app.component.ts) are the keys to your particular problem.

**Comment by carmenbranje** [comment]
Thank your for your help. I had removed the reference in app.module.ts I guess. Thanks again!!
