### ISSUE TITLE
Whats the best approach to styling?

### ISSUE THREAD

**Issue by carmenbranje** [500tech/angular2-tree-component#63]
Whats the best approach to styling the tree?

**Comment by adamkleingit** [comment]
Hi,

First of all refer to the styling document which shows the HTML structure
of the tree nodes:
https://angular2-tree.readme.io/docs/styling

You can also look at the source code of tree.component.ts and
tree-node.component.ts to see the existing style.

The tree components' encapsulation mode is set to none, so the easiest
would be to give a class or ID of your own above the tree, and style
everything scoped to that class / ID - then you will override the tree's
style.

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by carmenbranje** [comment]
One issue I'm having is with the hover states with the nodes.

Since lower level nodes are children of higher level nodes, the hover states remains on, on the parent even when I'm hovering over a child node.  So if I have a highlighting (backkground-color) for a node, and I hover over the root and then move down the the next level node, both the root and the child node stays highlighted. 

I guess this is more of a css issue than an issue with this component?

**Comment by isaacplmann** [comment]
Your problem is that you have a css rule like this:

.tree-node:hover { etc. }

when you want a rule like this:

.node-content-wrapper:hover { etc. }

**Comment by carmenbranje** [comment]
I see what you mean, but there's also the chevron to the left of the node-content-wrapper. How could I make the entire "node" background a certain color. I'll have to get the node-content-wrapper and span tags that hold the chevron to expand to take up all the tree-node.

**Comment by adamkleingit** [comment]
There's actually a PR that adds another wrapper around both.
But it is not backwards compatible.

Since this is at least the second time it's bothering someone, I might
merge it and make a breaking change version

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633
