### ISSUE TITLE
TreeNode.clearFilter() not working

### ISSUE THREAD

**Issue by andrevmatos** [500tech/angular2-tree-component#64]
Clearing filtering with `tree.treeModel.filterNodes('', true)` doesn't work on current version, because [this line](https://github.com/500tech/angular2-tree-component/blob/bddef385f7ba3e7c6e1292cb4f128f18f69fff5a/lib/models/tree-node.model.ts#L258) contains `([] || this.children)`, where `[]` always validate as true, and `forEach` don't recurse into children.

I believe that, for the desired behavior, it should be changed to `(this.children || [])` to make filter be correctly cleared.

**Comment by adamkleingit** [comment]
True!
I'll fix :)

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by adamkleingit** [comment]
Fixed in 1.3.1
