### ISSUE TITLE
Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by Gillardo** [500tech/angular2-tree-component#69]
Calling this method, which finds the node, but causes the below exception...

```
setTimeout(() => {
	let node = this.tree.treeModel.getNodeById(this.report.folderId);

	if (node) {
		node.toggleActivated();
	}
}, 0);
```

> 
> core.umd.js:3468 TypeError: Cannot read property 'nativeElement' of undefined
>     at TreeNode.scrollIntoView (tree-node.model.js:213)
>     at TreeNode.focus (tree-node.model.js:219)
>     at TreeNode.setIsActive (tree-node.model.js:201)
>     at TreeNode.toggleActivated (tree-node.model.js:209)
>     at save.component.ts:49
>     at ZoneDelegate.invokeTask (zone.js:225)
>     at Object.onInvokeTask (core.umd.js:6233)
>     at ZoneDelegate.invokeTask (zone.js:224)
>     at Zone.runTask (zone.js:125)
>     at ZoneTask.invoke (zone.js:293)

Tihs exception doesnt happen if it is the top level node, only when it is a child node within another...

I have even tried to increase the timeout to 1500, but still the same thing.

I am using 1.2.1

**Comment by Gillardo** [comment]
This now seems to be fixed in the latest version... but using toggleActivated doesnt seem to focus on the node when it is a child node??  How do you expand all the nodes so you can see the activated one @500tech-user

**Comment by adamkleingit** [comment]
You can either call `toggleActivated()` && `ensureVisible()`, 
or call `setActiveAndVisible()` which activates the node, expands all parents, and scrolls the view to make sure it's visible.
