### ISSUE TITLE
Drag and Drop hierarchy checking?

### ISSUE THREAD

**Issue by pixelchutes** [500tech/angular2-tree-component#73]
It seems it is possible to drag & drop a node onto itself. Also, you can apparently drag a parent node into one of its own children (if expanded), effectively resulting in a similar orphaned-node scenario.

Is this the intended behavior?

I believe the necessary checks could be manually added to prevent this behavior, but this felt fundamental enough to question whether or not it should ship as part of the core component.

**Comment by EinArzt** [comment]
There should definitely be checks to prevent this!

**Comment by pixelchutes** [comment]
To clarify, this appears to actually _remove_ the node(s) in question, rather than orphaning them. Not sure if this is the intended behavior, but if so it is very easy to accidentally remove a node like this.

**Comment by adamkleingit** [comment]
I agree, will be fixed in coming version

**Comment by adamkleingit** [comment]
Fixed in 1.3.3
