### ISSUE TITLE
Option displayField not working

### ISSUE THREAD

**Issue by krzysztofsaja** [500tech/angular2-tree-component#74]
It seems that option displayField: 'title' is not showing title key from object - only default "name" is working (Angular 2.0.0)

**Comment by pixelchutes** [comment]
Can you share some more code / example of you believe to be in error exactly?

I'm not personally experiencing any issue with `displayField`, in fact I'm heavily relying on it.

**Comment by krzysztofsaja** [comment]
Sorry, I've just found my mistake. I tried changing displayField to 'title' while I was using 
`<tamplate><span>{{ node.data.name }}</span></template> `, that overrides this settings. 
This issue can be closed. Maybe this use case should be mantion in docs

**Comment by pixelchutes** [comment]
Can you close the issue, please? Glad you got it sorted out!
