### ISSUE TITLE
Add an option to specify a "handle"

### ISSUE THREAD

**Issue by EinArzt** [500tech/angular2-tree-component#75]
An option to specify a handle for dragging & dropping nodes would be a great addition.
For a demo see here at "Drag handle and selectable text": http://rubaxa.github.io/Sortable/

**Comment by adamkleingit** [comment]
Hi,
you can solve this using the [treeNodeFullTemplate](https://angular2-tree.readme.io/docs/templates#treenodefulltemplate).
Add a handle and use the `treeDrag` directive on it

**Comment by tptshoe** [comment]
I've looked this over and tried a bunch of experiments, but I just don't understand WHERE to put the drag handle in the code referenced. Can you give a little more info?

I'm currently using #TreeNodeTemplate (see below). Can you provide a little more detail on how to put the handle where I've indicated? Thanks in advance!!!!

      ```
      <ng-template #treeNodeTemplate let-node let-index="index">
                <div fxLayout fxLayout.xs="column">
                  <div fxflex class="pi-name-text">
                    <!-- WOULD LIKE TO PUT DRAG HANDLE HERE -->
                    {{ node.data.name }}
                  </div>
                </div>
              </ng-template>
```
