### ISSUE TITLE
onDoubleClick event dosn't work

### ISSUE THREAD

**Issue by isupovs** [500tech/angular2-tree-component#76]
I upgraded my angular project to realease version and switched angular2-tree-component to 1.3.2. Now onDobleClick event never fires. According to [documentation ](https://angular2-tree.readme.io/docs/events)it still must work.
`<Tree [nodes]="nodes" [options]="options" (onDoubleClick)="onNodeDoubleClick(tree, node, $event)"></Tree>`
`onNodeDoubleClick($event) {
     console.log($event);
 }`

**Comment by isupovs** [comment]
I found this in source code `warning: 'This event is deprecated, please use actionMapping to handle double clicks'` for dblClick event. But there's no mention in documentation about it. So, actionMapping works good.

**Comment by adamkleingit** [comment]
True, updated docs
