### ISSUE TITLE
Weird: tree.getDragNode() returns wrong node

### ISSUE THREAD

**Issue by twmobius** [500tech/angular2-tree-component#77]
There is something weird going on with getDragNode.

According to the documentation ```tree.getDragNode()``` should return the dragged node but from what I've seen so far it seems that it contains only the destination node.

Also according to #71 onNodeMove does not work. Could you please help me out on this?

**Comment by adamkleingit** [comment]
getDragNode should return an object that has:
node property: the parent node
index property: the index inside the parent's children that points to the dragged node

Does that solve the issue?

**Comment by twmobius** [comment]
Yes this solves it thank you. Does it mention it on the documentation and I completely missed it?

**Comment by adamkleingit** [comment]
I'll update the docs properly. Thanks

**Comment by twmobius** [comment]
Thanks again :)
