### ISSUE TITLE
Node expand button can get out of line

### ISSUE THREAD

**Issue by Deftig** [500tech/angular2-tree-component#80]
I've got this problem where the content of my node is getting wrapped when there's not enough space. So far I have been able to style my way out of it.

![image](https://cloud.githubusercontent.com/assets/14015531/19372829/b49f9526-9202-11e6-8f4a-e01194582b8b.png)

**Comment by adamkleingit** [comment]
Hi,

can you share your CSS solution?

Thanks

**Comment by Deftig** [comment]
Ah so sorry! I meant I have NOT been able to CSS my way out (facepalm) - I got to the point where I decided if there is a CSS solution it would probably depend on a specific structure and that would be too brittle.

**Comment by adamkleingit** [comment]
What would be the desired behaviour in your case?

I need to do some refactoring to allow to override the entire node template, and not just the inner content. That would allow anyone to change the structure as they wish

**Comment by Deftig** [comment]
For any given tree I would have expected the text to stay inline with the toggle.
I like the way you have it at the moment where I only need to be concerned about the inner content of the node and let the toggle do it's thing - I was thinking it might do the trick to wrap both the toggle-children-wrapper and the node-content-wrapper up in another div to keep them inline. That's what I've been meaning to try out anyway

**Comment by adamkleingit** [comment]
There's actually another PR open on this.
It's not backwards compatible, but I think it's time I do this change.

In the future, I want to allow the users to override the outer template of
the node as  well.


-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by Deftig** [comment]
Sounds great - I look forward to it. I can definitely see the value of having control over the full node too.

**Comment by Deftig** [comment]
Small update - I unintentionally CSS'd my way out of this while attempting to override the toggle-children image to be a character from my font. My Less looks something like this:

 .toggle-children{
            font-family: 'my-font' !important;
            background-image: none;
            &:before{
                  content: "\e90e";
            }
}

It had the side effect of leaving the toggle on the same line as the node template.

**Comment by Deftig** [comment]
Hey Adam, I intend to write my own solution for this when I get time - (unless you were on the cusp of doing your own :) ) I was wondering if you had any pointers or pitfalls you can think of that I would need to watch out for?

**Comment by adamkleingit** [comment]
Thanks for the PR!
merged and fixed
