### ISSUE TITLE
Asyncroot - expanded

### ISSUE THREAD

**Issue by SimonaMilchevska** [500tech/angular2-tree-component#81]
Hello,

By setting the property **expanded: true** the Node is by default expanded. 
I also  set this property for the asyncroot but it is not working. Is this a known issue, or maybe i am doing something wrong?
Does someone esle has the same case, to have the async root expanded by default?

**Comment by adamkleingit** [comment]
It's a known issue, somehow there was no open github issue so thanks for opening.

**Comment by adamkleingit** [comment]
Hi,
version 2.4.0 fixes isExpanded on async children. Notice that this version has some breaking changes.
