### ISSUE TITLE
Can't resolve all parameters for TreeComponent after 1.3.4 update

### ISSUE THREAD

**Issue by mattbryan9** [500tech/angular2-tree-component#82]
Hi,

I get an error:
`Uncaught Error: Can't resolve all parameters for TreeComponent: (?)` in zone.js: 140
after upgrading to 1.3.4. I don't see anything in the changelog that might cause this--do you know how I might fix it?

Thanks,
Matt

**Comment by ezzkht** [comment]
Same issue here! Reverting back to 1.3.3 :(

**Comment by scosc** [comment]
any updates here ?
I get this has something to do with me using typescript 2, but didn't figure it out yet

**Comment by JulienNexonia** [comment]
Same here :-(

**Comment by adamkleingit** [comment]
Checking...

**Comment by adamkleingit** [comment]
Had a bad build - can you try with 1.3.5?

**Comment by mattbryan9** [comment]
Works for me! :)

**Comment by adamkleingit** [comment]
I had a bad build in 1.3.4.
Can you guys try with 1.3.5?

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by JulienNexonia** [comment]
Works with 1.3.5 ! Thanks !

**Comment by adamkleingit** [comment]
Awesome
