### ISSUE TITLE
Get Reference to element in node template

### ISSUE THREAD

**Issue by gkTim** [500tech/angular2-tree-component#84]
Hello,

how can I get an reference to an element in the treeNodeTemplate?
In my case it is in inline editor which I need to focus after an node is added to the tree, but I can't find a way to get a ref to this element so I can call the edit method.

My tree template looks like this:

``` javascript
<Tree #tree
       [nodes]="treeNodes"
       [options]="treeOptions"
       (onUpdateData)="treeDataHasChanged()"
  >
     <template #treeNodeTemplate let-node>
     <inline-editor #nodeEdit 
        type="text"
        [(ngModel)]="node.data.name"
        (onEdit)="beginEditable($event)"
        (onSave)="saveEditable($event)"
        name="node{{node.data.id}}"
        size="8">
      </inline-editor>
      <a (click)="addNode(node)"><i class="pull-right btn btn-xs icon-plus"></i></a>
      <a (click)="editNode(node)"><i class="pull-right btn btn-xs icon-note"></i></a>
      <a (click)="deleteNode(node)"><i class="pull-right btn btn-xs icon-trash"></i></a>
    </template>
  </Tree>
```

I'm able to get the ref to tree but not to nodeEdit. I've tried `ViewChildren` and `ContentChildren`.
Maybe I'm doing something wrong so maybe someone has a hint for me.

**Comment by pixelchutes** [comment]
@gkTim:

Can you pass the template reference variable `nodeEdit` to your function(s) in question? _(You'll need to update the method signature to accept the new argument)_

**Example**
```javascript
(click)="editNode(node, nodeEdit)"
```

However, this does not seem like an actual angular2-tree-component issue. For discussion/questions like this, I'd recommend going to: https://angular2-tree.readme.io/discuss

**Comment by gkTim** [comment]
Hi,

you are right so I've started a discussion here:
https://angular2-tree.readme.io/discuss/58075cda6d24211900953b6e

**Comment by adamkleingit** [comment]
I responded in the discussion. Closing this one.
Thanks for the discussions and help with the library guys!
