### ISSUE TITLE
Updated to 1.3.4 getting "Can't bind to 'nodes' error

### ISSUE THREAD

**Issue by carmenbranje** [500tech/angular2-tree-component#85]
Updated to 1.3.4 and am now getting

Can't bind to 'nodes' since it isn't a known property of 'Tree'. ("
                </div>
                <div>
                    <Tree [ERROR ->][nodes]="nodes" [options]="options"></Tree>
                </div>
                <div>
"): CoachingPlannerComponent@11:26
Can't bind to 'options' since it isn't a known property of 'Tree'. ("
                </div>
                <div>
                    <Tree [nodes]="nodes" [ERROR ->][options]="options"></Tree>
                </div>
                <div>
"): CoachingPlannerComponent@11:42
'Tree' is not a known element:
1. If 'Tree' is an Angular component, then verify that it is part of this module.
2. If 'Tree' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.

**Comment by adamkleingit** [comment]
Checking...

**Comment by saradalco** [comment]
Same problem of @carmenbranje.. 
Should I import the TreeComponent inside my app.component?

**Comment by adamkleingit** [comment]
I had a bad build in 1.3.4.
Can you check with 1.3.5?

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by saradalco** [comment]
Check this 
https://angular2-tree.readme.io/docs/getting-started

@carmenbranje you should import TreeModule in your app.module and map the library in systemjs.config.js.

**Comment by adamkleingit** [comment]
Closing this
