### ISSUE TITLE
TreeModel.isDraggingOver is called too often

### ISSUE THREAD

**Issue by SamuelBeliveau** [500tech/angular2-tree-component#88]
I have some performance issues when displaying a lot of expanded nodes in the tree.

One thing I've noticed is that if I'm typing in another input, unrelated to the tree, the keypresses are very slow.

I started debugging the tree and it seems that TreeModel.isDraggingOver is called on each keypress in that input field (again, an input outside of the tree). Moreover, that method seems to be called on all expanded nodes.

I'm using version 1.3.5.

Thanks.

**Comment by adamkleingit** [comment]
How do you know that this is the reason for the slowness? It's just a simple comparison

Anyway, there are 2 things I plan on doing:
1. Allow changeDetectionStrategy to be configurable. Any ideas how to do this but still support AoT?
2. Use MobX to manage state and react to changes

**Comment by adamkleingit** [comment]
Solved in 2.2.0 after refactoring the drag'n'drop feature
