### ISSUE TITLE
Is this treeComponent Compatible with angular 1.x

### ISSUE THREAD

**Issue by anjankumargowda** [500tech/angular2-tree-component#89]
Hi,
We are using the Angular 1.x version , where we wanted to implement the tree view with drag and drop. Can you please let us know about this tree component usage in 1.x of angular.

Please suggest any easy to plug treeview for us

Thank you
Anjan Kumar M

**Comment by adamkleingit** [comment]
Hi,
this version is only for Angular 2.
All the best
