### ISSUE TITLE
Can't find component name such as 'IActionMapping' defined in angular2-tree-component

### ISSUE THREAD

**Issue by johnking** [500tech/angular2-tree-component#91]
Hi there, 

I tried to mimic the example under `webpack` of angular2-tree-component into my `ionic-2` application (systemjs based), but I got the error: 
  - `Cannot find name 'IActionMapping' `, 
  - `Cannot find name 'TreeNode' `
  - ... 

My code: 
```
import { Component, Input } from '@angular/core';
import { TreeNode, IActionMapping, TREE_ACTIONS, KEYS} from 'angular2-tree-component';

const actionMapping: IActionMapping = {
  mouse: {
    contextMenu: (tree, node, $event) => {
      $event.preventDefault();
      alert(`context menu for ${node.data.name}`);
    },
    dblClick: TREE_ACTIONS.TOGGLE_EXPANDED,
    click: (tree, node, $event) => {
      $event.shiftKey
        ? TREE_ACTIONS.TOGGLE_SELECTED_MULTI(tree, node, $event)
        : TREE_ACTIONS.TOGGLE_SELECTED(tree, node, $event)
    }
  },
  keys: {
    [KEYS.ENTER]: (tree, node, $event) => alert(`This is ${node.data.name}`)
  }
};

---
```

__I can manage the example working by commenting out the uses of the those components above.__

_So my question_ is how to use those components exported by angular2-tree-component? I even tried to add `IActionMapping` into `app.module.ts`

```
@NgModule({
  declarations: [
    ... 
  ],
  imports: [
    ...
    TreeModule, 
    IActionMapping,
  ],
...
```
But it did not help.

thanks for your help!

-John

**Comment by adamkleingit** [comment]
Hey,
You don't need to import the IActionMapping in the angular module.
Can you please send the complete original error that you get?
Thanks

**Comment by johnking** [comment]
@adamkleingit 
Hi Adam , 

  Thanks for your reply!
  I believe I messed up my dev environment because the errors are disappeared after re-building my my project.  

  By the way, I have integrated this `tree-component` into my project, and it works __perfectly__! I want to thank all the people behind this project!

Best Regards

-John
