### ISSUE TITLE
Wait for async expand-function

### ISSUE THREAD

**Issue by awallat** [500tech/angular2-tree-component#96]
Hi,

a needed feature is to wait for a node to be expanded. When I load my children asynchronously then I want to be informed when the node finally got it's data and is expanded, so that I can continue to expand a node from the next hierarchy level for example.

Or is there another way and I missed it in the documentation?

If I get a promise back from the expand - function, it'd be perfect. Thanks!

P.S.: If I find the time I could also try to implement this on make a pull request.

**Comment by adamkleingit** [comment]
Hi,
This is a known problem. If you can make a PR for this it would be greatly appreciated!

**Comment by JulienNexonia** [comment]
+1

**Comment by awallat** [comment]
I just created a PR #106 where the expand - function returns a promise. It works for my scenario.

We could also add a new function now that automatically expands a whole path. For this I could add another PR that adds the implementation of the following signature:

`expandPath(path: string[]): Promise<any>;`

Let me know if it's needed or better should be implemented on their own.

P.S.: Are there any tests?

**Comment by adamkleingit** [comment]
I'm still thinking about the PR, I understand the need but I'm thinking if there's a better way to do it.
Tests - on the list.
Version 2.4.0 fixes isExpanded on async children. Notice that this version has some breaking changes.

**Comment by s0x** [comment]
I think this is still an issue, isn't it? I'm trying to find a way to do expandPath() with async children. Is there a way to do so, which I can't see at the moment?

**Comment by adamkleingit** [comment]
I will merge it hopefully ASAP

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633
