### ISSUE TITLE
IE11 problem, nodes will not expand

### ISSUE THREAD

**Issue by jesben** [500tech/angular2-tree-component#99]
First of all thanks for an awesome tree component. I'm running version 1.3.5 in an Angular cli app with webpack. In Chrome it works, but in IE11 the nodes will not expand!? If I turn devtools on in IE 11 it works!!

**Comment by jesben** [comment]
Same problem in Microsoft "Edge"

**Comment by adamkleingit** [comment]
Very strange. Have you been able to figure out why it happens?

**Comment by jesben** [comment]
I'm running 1.3.6 now and everything is working perfectly, tested it in newest Chrome, Firefox, Mircosoft Edge and IE 11, what an awesome day, thank you!

Also demo at https://angular2-tree.readme.io/docs is now working in Edge and IE11.

**Comment by adamkleingit** [comment]
Great :)
